### ISSUE TITLE
Entity Tree perf issue. 

### ISSUE THREAD

**Issue by DaveTheGameDev** [OurMachinery/themachinery-public#1007]
- **Version:** Latest Binary Release (2022.1)
- **OS:** Windows

@simon-ourmachinery 
Adding many objects to the scene and selecting one of them in the entity tree, causes fps to drop to 4 from 144

![image](https://user-images.githubusercontent.com/21057342/153372469-0a98dd2c-93e2-4ab3-8315-6c656a7c2d25.png)

**Comment by simon-ourmachinery** [comment]
2 traces of the current master ... its super slow trace is when selecting and theotherone is not selecting. I had around 6k boxes
[trace_2.zip](https://github.com/OurMachinery/themachinery-public/files/8042749/trace_2.zip)

**Comment by leonardo-ourmachinery** [comment]
@DaveTheGameDev May I also ask you if the performance hit is there even if you just hover over the entity tree, without selecting anything?

**Comment by DaveTheGameDev** [comment]
@leonardo-ourmachinery  It was happening mostly when I selected things. Duplicated things a ton and was mostly just messing around with large numbers of entities, For some reason though I cant repo it with a  quick test, where as before I was in the engine for about an hour messing with stuff,

I can confirm duplicating/deleting large amounts of entities does indeed cause the editor to stall or even crash.

**Comment by leonardo-ourmachinery** [comment]
@DaveTheGameDev I pushed a couple of optimizations to master.
I indeed found it strange that on my machine the hit was not so big as yours and @raphael-ourmachinery 's machine.

But not it should be gone. The problem was that we were sorting _all_ the children of the entities that were visible, every frame.
Not we're caching the list so you should see no spikes at all when hovering over the entity tree.
(Though the list will still be invalidated when you add/remove/reorder children of that entity, so there will be one frame afterward were we'll have to recompute the list from scratch, but I don't think there's anything we can do about that).

Closing this for now, there's the other issue that's tracking the duplication/deletion problems.

**Comment by DaveTheGameDev** [comment]
Sounds good, will test when I can.
