### ISSUE TITLE
SSAO issue

### ISSUE THREAD

**Issue by DaveTheGameDev** [OurMachinery/themachinery-public#1008]
- **Version:** Latest Binary Release
- **OS:** Windows

SSAO causes outline on objects when against the sky component

![image](https://user-images.githubusercontent.com/21057342/153373616-785c546f-5312-4f5f-a345-0ac05168006a.png)

**Comment by DaveTheGameDev** [comment]
Outline is not visible against other objects in my scene.

**Comment by DaveTheGameDev** [comment]
Looks like this has been fixed in master  :)

**Comment by huseyin-ourmachinery** [comment]
Yes, thank you for reporting it. There was an early exit code that prevents running SSAO on sky pixels for more performance. But the problem was; if we discard some pixels, pixels on edges of the objects when against the sky weren't complete their full rotations because some of the neighbor pixels from 4x4 pixel area weren't processed. (We use 4x4 noise for rotation)
