### ISSUE TITLE
Properties gets added when importing entities and assets from another project over collaboration

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1013]
- **Version:** Git Master Branch
- **OS:** Windows

When running two collaboration clients, and one client imports a .tm_dcc_asset from another project, the second client will get new properties added which removes the visuals of all meshes and textures. The important change is a property `id: ""` which does all the difference.

If we save the imported .tm_dcc_asset on both clients here is the resulting files:
Client which did the import: [battery_01.zip](https://github.com/OurMachinery/themachinery-public/files/8049630/battery_01.zip)
Client which recieved the import over collaboration: [battery_01.zip](https://github.com/OurMachinery/themachinery-public/files/8049634/battery_01.zip)

**Comment by Tisten** [comment]
A repro for this is to start the-machinery with an empty default project and save it. Now start a local collaboration host, and another the-machinery editor as client. Let the client use the saved default project as the import source, and import the core/camera.entity into the root folder of the asset browser. Now do a save on the host and compare the "Default Project/camera.tm_entity" and the "Default Project/core/camera.tm_entity". Note the extra fields of `name`, `display_name`, `id` and `tooltip`, all with the empty string as the value

**Comment by niklas-ourmachinery** [comment]
I was able to repro it using the steps above. Notes:

* If you don't have a client and just do the steps on the host, the extra fields do not appear.
* If you save the project from the client after import the extra fields do not appear.

So something happens when the imported data is synched over the network. It looks like the extra fields are getting tagged as "overridden" even though they are not... it is curious that it only happens for the "tm_graph_input" type though... investigating further...

**Comment by niklas-ourmachinery** [comment]
Fixed in master
