### ISSUE TITLE
When importing from another project, try to avoid duplicating data

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1015]
One use case we have had is to make a copy of a project, work a bit on it locally and to later join it to the original project by importing the new assets (entities and graphs) created on the copy.

In this case the copy and the original will have most of the assets and the hierarchy structure in common. So when importing something which has dependencies, it is very likely that those dependencies will already exist in the same place, in an identical version in the target project. It would save a lot of clean-up work if all dependencies weren't duplicated in this case, but the imported asset would reference to the existing resources in the target project.

This improvement could be taken much further. But the suggested improvement already gives a lot of benefit, it is contained to only check for identical paths and resource versions, and much of the logic to implement this seems to already exist.

**Comment by niklas-ourmachinery** [comment]
Agreed, that would be nice.

Checking for equality is not 100 % straightforward though, especially when it comes to references. I.e. to test two objects for equality we have to test that all the objects they reference are equal. But references do not necessarily form a tree structure, they can be cyclical (A references B and B references A), so we can't do a straightforward recursive descent to check for equality.

It can get very wonky like objects A and B can be considered equal if their referenced objects C and D are equal. But C and D reference A and B, so C and D are equal only if A and B are equal. Not impossible to sort out, but a little bit involved.

**Comment by niklas-ourmachinery** [comment]
Agreed... I'll try to get the first step in soon-ish and then we can take it from there.

**Comment by niklas-ourmachinery** [comment]
Thinking about this a bit more... I'm not 100 % sure you *want* to compare equality... maybe if the thing you are copying refers to a `brick-wall` texture and you have a `brick-wall` texture, you want to use your existing one rather than importing a new one... 

When I tried it with an equality match it failed to patch the geometry-material, because it contains a reference.

I've pushed an experiment to `master` -- this one does *not* use an equality compare... instead it will just patch the reference if it finds one with a matching name.

It's behind the "Match Reference on Import" feature flag -- so enable that in order to try it out.

**Comment by niklas-ourmachinery** [comment]
https://github.com/OurMachinery/themachinery/commit/fe79d19731f6fcc2969a5b0e979430c15fd332d2

**Comment by Tisten** [comment]
For the `brick-wall` example, you only want to use you existing brick-wall if it was identical. Otherwise you might overwrite a red brick wall with a yellow one. So for the initial implementation I would rather want to it to be safe, than to replace references based on a name check. If the reference was a buffer, so the name was a hash of the data then a name check would suffice, but if the reference is a graph, an entity or any other json based asset, then the name is no good.

A slightly better option than to reject it would be to ask the user for every reference where then name matched. But it might be hard for the user to know the answer without some kind of diff tool.

**Comment by niklas-ourmachinery** [comment]
Ok I put back the equality test -- I also implemented an equality test for references (will fail on cycles). Try it out and let me know how it works.

Some control over how references are patched could be nice... but I don't really like throwing complicated modal dialog boxes in the user's face... Might be better to have some kind of helper tool that makes it easier to patch references after the import has completed.

**Comment by Tisten** [comment]
Thanks, an initial test of "reimporting a whole small world entity" reduced the duplicated dependencies from 151 to 48.
The types of the "remaining ones/out of the total" are:
2/2 Asm
6/65 Creation
11/22 DccAsset
19/22 Entity
9/9 Entity Graph
1/1 PhysicsCollision

All Tag and Clip assets were de-deduplicated.

I did set a few breakpoints in `deep_clone__is_equal()` and all of the ones remaining were thrown out because of being marked as cycles in the `equal_map`. There were two types which were guitly of these cycles, one was DccAsset, and the other one was PhysicsCollision which I found a bit curious since they had themselves in the reference set.

**Comment by Tisten** [comment]
I added this:
```
                    if (from_id.u64 == from_set->data[added_i].u64 && to_id.u64 == to_set->data[added_i].u64)
                        continue;
```
before this line:
https://github.com/OurMachinery/themachinery/blob/de3731639582d85ce90197451ce9595c11df9b47/foundation/the_truth.c#L3632

and it fixed the PhysicsCollision. But I haven't investigated what the use of that reference to self is good for. :)

**Comment by niklas-ourmachinery** [comment]
@Tisten I implemented a solution for recursive references.

While evaluating `A == B?` we will for the purpose of recursive checks assume that `A == B` (i.e. `deep_clone__is_equal()` will return *true*). This should make `A == B` return *true* if the *only* differences are the recursive references.

Let me know how this works out in your tests.

**Comment by Tisten** [comment]
I've done a whole bunch of tests, and it looks promising now. I've seen a bunch of bad things, but I will only try to list the things which I can repro or have explanations for.

When trying this latest version, I did the same test as above, and the result this time was that only 3 entities were duplicated. Not perfect but much much better. The imported entity itelf became very different from what was imported, but if I understand the json correctly then the differences are actually data which is getting mended, after being "broken" before. So the import worked a bit like a sanitizer. :) I need to look closer to see if any of the changes were incorrect, and I haven't debugged why those 3 entities were duplicated.

I also tried it on the world entity of https://ourmachinery.com/files/procedural-forest-09-02.7z where I got 15 dcc_assets and 23 entities duplicated when importing it into a copy of itself.
So what I did was:
* Open procedural-forest-09-02.the_machinery_db and accepted the "core update"
* Save the project as a directory, to two different locations
* Now I selected the first saved folder as an import project.
* I renamed the world entity in the opened project, then dragged the other project's world entity into the opened project.
* I checked the created "world dependencies" folder for what got duplicated.

But later I closed the editor, copied the unmodified saved folder to another location and opened the editor with this project. Now I didn't get any duplicated dependencies at all!

So the "in memory state" which I got from the `procedural-forest-09-02.the_machinery_db` was different from the state which I got from the directory on disk, even though I had just used that state to save the data on disk. I would guess that the "data upgrade" was't done to completion in memory, but it was when saved to disk, but I have not verified this. But if that is the case then it worries me since our server is sometimes running for a week between restarts, and if the in-memory state then becomes different from a newly loaded state then that will make it harder to create local snapshots and later reimport the work into to server's state.

**Comment by niklas-ourmachinery** [comment]
It's a bit tricky to tell exactly what went wrong without digging deeper. But there is some heuristic stuff in the algorithm that can fail.

When a reference for example points to a subobject of a subobject of a subobject of an asset... we need to match that reference to an object in the destination truth. We match the assets by name, but how do we match a subobject from all the possible objects in a subobject set?

We can't do it by UUID, because those can differ between the Truths... we could do it by equality, but that would be very expensive because we would have to test for equality with each object in the subobject set.

So currently we just do it by index... i.e. we expect to find the object at the same index in the subobject set in the two different truths... but the sets could be reordered in the Truth and still be the same "set" so this heuristic can fail. But I can't think of any other good way of doing this... except we could potentially add more heuristics... like trying to match objects by "name" or "type" if the initial match by index fails.

It's also possible that there is some background task running that's updating the in-memory state and causing it to be different from the saved state... though I would think that a Save would force all those tasks to finish.

But if you find specific problems where something goes wrong you can post new issues and Ican look into it and see if I can suss out what the issue is.
