### ISSUE TITLE
input/outputs inside graph component of entity exposed on scene entity node when pulled into another graph

### ISSUE THREAD

**Issue by TobiasElemental** [OurMachinery/themachinery-public#1027]
Sorry for title being a mouthfull...

I will try to explain:
- An entity has a graph component - this graph has inputs and outputs - I make them public
- When pulling this entity as a scene entity into another entities graph - I kind of expect that the inputs and outputs of that scene entities graph are visible and that I can manipulate them inside of this other graph. As opposed to having the call set/get remote variable and type in correct strings.

I find that it is more common I want to manipulate an entities logic inside another graph in runtime as opposed to changing exposed values in a scene.

The input/output concept could be REALLY strong, and make things much more readable if scene entities sort of "brought with them" this and potentially other information out into other graphs when pulled in as scene entities. The flow of get entity, remote variable works - but is not as intuitive and prone to errors I feel.

**Comment by simon-ourmachinery** [comment]
A comment on Input/Output on Entity Graphs. 

They are a "compile-time" things, when the current graph representation is transformed into something the interpreter can understand they are resolved. This would mean you could not change such things at runtime. 

This would mean:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/70658708/154554567-80120a9a-a4e4-41b1-98eb-03238a2c4587.png">

the output variable has no meaning at runtime since it would just not exist.
