### ISSUE TITLE
Reimport doesn't work over collaboration

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1093]
- **Version:** Git Master Branch
- **OS:** Windows

Use the attached project and mesh for the reproduction case:
[reimport.zip](https://github.com/OurMachinery/themachinery-public/files/8141292/reimport.zip)

* Open the-machinery and load the "Reimport" project from the .zip file, and make the editor a LAN Host
* Open another the-machinery and connect it as client
* On the client, use the asset browser to find `dependencies/arm_holding_arm_01_arm.dcc_asset`
* In the properties tab, press `Reimport From...`
* Select the `arm.fbx` from the .zip file
* Use the File menu and `Save Project As...` on the client
* Use the File menu and `Save Project As...` on the host
* Disconnect the client and reconnect it. Note that the mesh is gone.
* Compare the `dependencies\arm_holding_01_arm.tm_dcc_asset` file in the saved client and host projects.

**Comment by karl-zylinski-ourmachinery** [comment]
I noticed that the reimport uses set_uuid to make sure the old and new object are virtually the same. This caused the previous collaboration import bug as well. I'm looking into how to make set_uuid work over collaboration.

**Comment by niklas-ourmachinery** [comment]
@karl-zylinski-ourmachinery I don't think this is the issue here.

It's true that we have no way of "synching" UUID changes -- UUID's shouldn't change, since they are what uniquely identify objects.

But `retarget_write()` doesn't *actually* change the UUID of any object.

It retargets a write that was originally for object B to instead write into object A. It uses `set_uuid()` to change the UUID value in the *write data* from `B_UUID` to `A_UUID`. That means that when the write is comited *A_UUID* gets written as the UIUID of the object A. So the UUID of A doesn't actually change.

**Comment by karl-zylinski-ourmachinery** [comment]
@niklas-ourmachinery I might be confused, but: `set_uuid` updates the local UUID -> object ID mapping, and when the other peer in collaboration runs `private__deserialize_change`. That function will lookup the object ID using the UUID -> ID mapping, which has only been changed on one of the peers?

**Comment by niklas-ourmachinery** [comment]
Hmm... I think this is a bug in `retarget_write()`... it shouldn't update the UUID map to point to `obj->object`... since the write is being retargetted to `id`, the UUID should still point to `id`. I'll fix it...

I can't thinking of anything that would require the `set_uuid()` there... but a bit hard to tell... I'll remove it and we'll see what happens.

**Comment by niklas-ourmachinery** [comment]
Ok, I made a fix just removing `set_uuid()`... let's see how it works.

If we discover any issues with this... it might be that we need to change the UUID of `obj->object` *without* updating the lookup tables, so that they still point to `id`, but right now I can't see any reason for needing to do that.
