### ISSUE TITLE
Corrupt data in collaboration cache caused crash

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1108]
- **Version:** Git Master Branch
- **OS:** Windows

One person couldn't connect to our collaboration server because of a crash in the rending code happening after loading the project data from the host. In the end he managed to resolve the issue by clearing the collaboration cache, so the issue must have been that one of the files stored in that cache wasn't correct, but it was still accepted by the engine until the graphics driver crashed when using it.

It might be an idea to at least verify size, and when running in safe mode also do hash validation of the files.

**Comment by niklas-ourmachinery** [comment]
Most likely the engine shutdown/crashed while the collaboration cache files were being written.

As a quick fix I implemented write/rename instead of writing directly to the target file which should hopefully fix this.

If the issue is still occurring after this fix we could look into hash verification or possibly just disabling the collaboration cache in Safe Mode (both potentially pretty expensive).
