### ISSUE TITLE
Add "Change prototype" for entity instances in entity tree

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1155]
When clicking on an Entity Asset in the Asset Browser, the properties tab will show the Prototype, and this field can be changed.

But when adding an Entity Asset in another Entity, there is no easy way to change which prototype is used.
The way I've found is to put the new Asset Entity into the Entity Tree, and then redo each override one by one manually.

**Comment by leonardo-ourmachinery** [comment]
Fixed in master: you can you change the prototype via the prototype picker for both the Entity Root and children.

Notice that this is still not allowed:
-Create an entity asset (call it foo)
-Make its prototype be the "box" entity
-Add an empty child to it
-Add a "sphere" child to it
-Create a new entity asset
-Make its prototype be the "foo" entity
-Override both the empty children and the sphere children

You _cannot_ change the prototype of neither the empty child nor the sphere child here, as they are "overridden" children, so you can override them and change stuff about them, but you cannot change their prototype.

**Comment by Tisten** [comment]
I have a question about the feasibility of keeping overrides when changing the prototype.

Here is what I really want to use this feature for:
- I have modified "core/sky", and this was a bad move since it gets overwritten/reverted any time core is updated.
- So I want to create a "customized_core/sky" which uses "core/sky" as a prototype but overrides and adds to sky
- And now I want to change the prototype of all entities which have "core/sky" in them to use my new version. But if my world have overridden a property of sky, then I want to keep my override. This ought to work since sky is still part of the prototype I'm using.

I understand that my usecase is a special case, and that in other cases the new prototype might not at all have the same layout as the old. But if there would be a way to keep as many overrides as possible, then that would be awesome!

**Comment by niklas-ourmachinery** [comment]
The tricky part in implementing this is understanding the "mapping" between objects in the old and the new prototype.

Say that the old prototype has a list of children A_1, A_2, ... A_n, one of which (A_i) you have overridden.

Now you switch to a new prototype that has children B_1, B_2, ..., B_m. How do you know which B_j corresponds to A_i.

There is no straightforward, guaranteed-to-work way... some options:

* You could match by index, but the order of objects in a set is undefined.
* You could match by name, but not all objects have names and names are not required to be unique.
* You could match by equality, but B_j might not be equal to A_i.

**Comment by Tisten** [comment]
I fully grasp that. For the "index" case, the `child_sort_values` perhaps could make the entities in a set to have an order. Components are guaranteed to be unique in an entity, but the problem is with mapping entities.

For my very specific case it should work to search for UUIDs in the prototype hierarchy to find the mapping, i.e not just look at the prototype's objects, but check the prototype's prototype and so on. But that only works if you want to inject a prototype in the middle.

If I have a `ProtoBase <- ProtoMiddle <- TopInstance` and want to remove ProtoMiddle and just set ProtoBase as the prototype of TopInstance then UUID no longer works. And indices wont work since the ProtoMiddle might have a different sort order, and also have new entities added compared to ProtoBase. And names wont work as you said, they are not unique. And equality neither.

So for this case, it might work if you know the whole prototype chain before the change, and can identify which UUIDs were part of the inheritance chain before and after.

I think the same could help when switching from `ProtoBase <- ProtoMiddle1 <- TopInstance` to `ProtoBase <- ProtoMiddle2 <- TopInstance`

But in a case where you just duplicate a protoype and change from one of them to the other, there wont be any UUIDs to help neither.

**Comment by niklas-ourmachinery** [comment]
Yes, I don't think there is any great solution for this... best is probably to match by name if possible and otherwise by index... but I'm not sure if that will behave well enough to be worth implementing...

Part of this comes from our decision to use IDs for object references. If you had a "looser" approach where you used names for references and overrides, i.e. something like:

~~~c
prototype = "/core/sky.entity"
overrides = {
   .sun.light.color.r = 1.0
}
~~~

Then you could change the prototype and things would be ok whether that project had a `sun` object or not.

But this approach comes with other drawbacks -- it is easier for references to break, you need lots of string processing to resolve them, etc.
