### ISSUE TITLE
Pinning doesn't work in the Entity Tree

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1163]
- **Version:** Git Master Branch
- **OS:** Windows

Repro:
* Open the editor with default layout
* Open a second "Entity Tree" tab
* Open an entity and pin it in one "Entity Tree" tab
* Open another entity. Now the pinned tab is blank

**Comment by niklas-ourmachinery** [comment]
This is because the entity tree doesn't use the normal "focus" mechanism of tabs... instead it just shows whatever is in the scene tab (i.e. by reading `TM_TT_TYPE__SCENE_TAB`).

I agree it would be preferable to make the Entity Tree behave more like other tabs... will need some thinking on how to make it work.

**Comment by leonardo-ourmachinery** [comment]
I pushed to master a fix, as far as I can tell now the Entity Tree behaves as expected when pinning an object.
@Tisten feel free to reopen if you notice anything weird.

**Comment by Tisten** [comment]
An initial test looked good. Thank you!
