### ISSUE TITLE
TM_PRE_ALPHA_DIR quickly gets bloated with DLL copies

### ISSUE THREAD

**Issue by cyberfrank** [OurMachinery/themachinery-public#118]
As known, due to hot-reloading plugins, all DLL files gets renamed as `tm_hot_reload.xxxx`. As it appears, each plugin is duplicated at most **one time** without concern for how many times a hot-reload is performed. However, `the-machinery-dll` gets copied **for each** reload and quickly bloats the `bin` folder. 

It would be nice if The Machinery would cleanup all `tm_hot_reload` copies as an additional step or hook when closing the application. I do not know if this is possible directly from `the-machinery-dll`, but I personally consider this a mild annoyance. I do not know if `tmbuild` handles this in some way either.

**Comment by niklas-ourmachinery** [comment]
A DLL gets copied if it has been modified. So if you see `the-machinery-dll` copied on each reload it's probably because you are modifying something in that project.

Old `tm_hot_reload` copies are cleaned up on application *start*. Cleaning them up on shutdown is more tricky, because at that point they are open by the application which prevents them from being deleted. In theory, the application could release all handles and then delete them, but it's a bit fragile and tricky, since calling any DLL function after that would crash.

But if your main concern is disk bloat, deleting the unused copies at startup should take care of that, right?

I would love to find a better way to do hot reloading without having to do these `tm_hot_reload` copies. But so far I haven't find a good way with the way Windows file locks work and the way the Visual Studio debugger holds on to them.
