### ISSUE TITLE
Propagating Entity Graph changes to Prototype breaks wires

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1205]
- **Version:** Git Master Branch
- **OS:** Windows

This bug could be related to https://github.com/OurMachinery/themachinery-public/issues/1124

Repro steps:
* Create a new project
* Add an Entity Graph component to the world entity
* Add two nodes to the graph and connect them (A -> B)
* In the "Asset Browser", click "Instantiate" on the "world" and open the new entity
* In the Entity Tree, override the Entity Graph component and open it.
* Add a new node between the two existing nodes (A -> New -> B)
* Select the Entity Graph in the Entity Tree and choose "Propagate Changes to Prototype"
* Note that the wires are not connected as they should be

It is also worth noticing that after propagating the changes, the instance for "Entity Graph: world (instance)" (i.e the previous override) is still open and can be edited, even though it is no longer marked as overridden.

**Comment by Tisten** [comment]
Recorded it to show the issue ![Propagate](https://user-images.githubusercontent.com/6726075/160083427-cac7a28a-68f1-4212-82f7-768127c1939a.gif)

**Comment by karl-zylinski-ourmachinery** [comment]
Looking at fixing this.

In the meantime, if you right click the greyed out connection before propagating and choosing 'remove from instance' then it will propagate correctly. This may seem strange, but the greyed out connection is only disabled because the new one you added sort of "overloaded" it, but this is purely done during the graph-from-truth-import, marking the connection as disabled. It is not marked as disabled in The Truth, which is why it doesn't propagate properly.
![bild](https://user-images.githubusercontent.com/57644882/160342336-7c64c0fa-856d-466b-b874-88325292610a.png)

**Comment by Tisten** [comment]
Thanks for the workaround @karl-zylinski-ourmachinery

I don't see a similar workaround for https://github.com/OurMachinery/themachinery-public/issues/1124 so perhaps the bug is different then? It would be great to have that fixed as well.

**Comment by Tisten** [comment]
I just tried you workaround, and it didn't work as expected. I will try and make a new recording.

**Comment by Tisten** [comment]
![Bug](https://user-images.githubusercontent.com/6726075/160349106-2968eac9-eeb1-4acf-a852-477fcf878765.gif)

Started in an entity instance. The entity prototype has a entity graph component which has been overriden in the instance.
Steps in the recording:
1. Override of a node just to be able to move it
2. Add a new node as output of the moved node
3. Connect the output of the new node to the old output of the moved node
4. Applied the suggested workaround by removing the wire from this instance
5. Propagated the changes to prototype (the menu item was outside the recording)
The result was that the wire from the moved node to the newly added node got removed

**Comment by karl-zylinski-ourmachinery** [comment]
@Tisten I have fixed both issues now. Fix for the propagation of 'implicitly disabled' connections is here: https://github.com/OurMachinery/themachinery/commit/397064c4cb05647795d07796217ce372f03eb179 (added an aspect to TT that lets us do some prep work on the graph before it is propagated)

Fix for your second issue is here: https://github.com/OurMachinery/themachinery/commit/93ddb6dc0cf23fda1ebcf6a9c13de678d365db51 This was due to us not mapping up the instanced node -> prototype properly when doing the propagation.
