### ISSUE TITLE
Minor UI - clipping of workspace names

### ISSUE THREAD

**Issue by jamesmintram** [OurMachinery/themachinery-public#1210]
-Git Master
- Windows

Clipping of workspace names

![image](https://user-images.githubusercontent.com/108040/160297607-0f21b008-6e11-440c-a0f7-730dbfc693c0.png)

**Comment by niklas-ourmachinery** [comment]
I see two possible alternatives:

* Scale down text if it would clip.
* Still clip, but left-align the text if it would be clipping.

Could also use some combination -- i.e. scale down, but do not make the size < 50 % (because at that point it would probably be unreadable anyway)... then left-align and clip if it's still too big.

**Comment by DaveTheGameDev** [comment]
Could be interesting to have a horizontal workspace bar along the top chrome tab style?

**Comment by niklas-ourmachinery** [comment]
I added the left-align thing... also added tooltips so you can see the full name.
