### ISSUE TITLE
Clickable error messages in console tab

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1266]
__Feature request:__
Add support for clickable error messages which opens an asset and teleports to the error.

__Example:__
When working in the-machinery I frequently get error messages in the console tab similar to `Trying to lookup property of NULL truth object`

As a programmer I can set a breakpoint, check the callstack and find which system this comes from, and what object the owner of this null object is. In our project, it frequently turns out to be an Entity Graph which is broken.

In cases like this I would like to instead get a clickable error message saying `Error in Entity Graph of Entity 0x1234000000B7: Node 'Set Transform' at pos x, y got a null entity as input` which would open the graph and highlight the node with the issue.

__Details:__
This would require a standard for how to write such error messages so the tab can create the link, and support in each tab for what to listen for, open the asset and teleport to the location.

**Comment by DaveTheGameDev** [comment]
Plus one to this. I have tried clicking error messages to be taken to the problem out of habit.

Would be a good feature.

**Comment by simon-ourmachinery** [comment]
Just a note not a solution:

> As a programmer I can set a breakpoint, check the callstack and find which system this comes from, and what object the owner of this null object is. In our project, it frequently turns out to be an Entity Graph which is broken.

One can also enable the "Print Call Stack on Error" feature flag.

**Comment by simon-ourmachinery** [comment]
Oh yeah, my side note was more for the NULL issue any issue that needs no context besides what function is called. Otherwise, I am seeing the value. It is just not that easy to implement since there needs to be some context passed along with the error report. Which requires some thinking on how and what exacly.

**Comment by Tisten** [comment]
One rather easy option could be to make the job system keep user_data. E.g a hash and a pointer stored in a linked list, making it possible to optionally tie data to a running job. This way the assert could store a note that it was triggered from any plugin, on any depth of the call stack. Normally the list should be a nullptr, but in exceptional cases it can be assigned with debug info useful when reporting errors. And any time a job finishes, the user_data list is cleared. Memory for that data can then be allocated with a frame allocator which dealloc at end of the frame.

**Comment by niklas-ourmachinery** [comment]
It's a bit tricky in general because:

* This error occurs in a low-level function that doesn't have enough information to give a high-level error message.
* This is an "unexpected" error that comes from an error in the code... (error messages like this should never be printed from user data errors). We can't really write code to handle coding errors.

One thing I've done in past projects which might work is to have a concept of an "error context" which is a per-thread stack of high level objects that are being processed. If an error occurs, the content of this stack could be printed which could point to the source of the error.

**Comment by leonardo-ourmachinery** [comment]
@Tisten I agree with you, these error messages should at least tell you what Entity Graph has caused the error:
![image](https://user-images.githubusercontent.com/70660839/170284330-8f8cfa9a-ce29-4588-892e-9fb6b78f9310.png)
In addition to doing this, once we have clickable error messages, clicking on the error message in the console tab is expected to teleport you to the exact node that caused the issue.

I'll take a stab at both.

**Comment by niklas-ourmachinery** [comment]
Ah, thanks for clarifying... true, that is a runtime error that can't be easily detected in the graph itself.

I like the approach of configurable errors/IDs and the game project being in control over what events should be "hard stops".

I've flip-flopped myself many times over whether it's best to have errors blow up as soon and as loudly as possible, or to try to ignore them as much as possible and keep on chugging... it makes sense to leave that up to the project.

**Comment by simon-ourmachinery** [comment]
> I do like the idea of having both a log and an error/warning view (e.g like is Visual Studio).
I do like this very much, especially in the combination of project-specific IDs this allows for better error communication towards the user. For example, any kind of logging from the headless mode could go there instead of just the console.

**Comment by leonardo-ourmachinery** [comment]
I've pushed to master a first version of clickable errors.

There's a new macro called `TM_ERROR_WITH_ID()` that will push down a `tm_tt_id_t` together with the message.
The console tab will then check if the error has an associated `tm_tt_id_t`. If it does and the object type has a valid `tm_tt_aspect__goto_error_i` then it will show a "clickable" error icon instead of the vanilla "cross" icon in the console tab.
Pressing the button will simply "trigger" the `goto_error` function of the aspect.

Here's a small demo:
https://user-images.githubusercontent.com/70660839/172631309-4ea49377-8c81-4e30-a17c-ab460bbc531d.mp4

I will leave the issue open for a bit, mainly to gather feedback on the UI (icons, colors, etc).

**Comment by leonardo-ourmachinery** [comment]
Closing this now.
