### ISSUE TITLE
An entity can get multiple components of the same type from prototypes

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1276]
- **Version:** Git Master Branch
- **OS:** Windows

Repro steps:
1. Start the-machinery with a new project
2. Instantiate the world entity in the asset browser
3. Add an Entity Graph component to the new "world (instance)"
4. Open the prototype, i.e "world", and add an Entity Graph component to it as well
5. Now go back to the "world (instance)" and note the two Entity Graph components below the root node

You can get as many components of the same type as you want in the same entity by repeating this workflow.

**Comment by Tisten** [comment]
It might just be the old conservative programmer in me, but I would like an instance to inherit its prototype exactly, and not to be able to bypass it and get values from the prototype's prototype if those values are removed from the protoype. It adds mental complexity, I would expect it to add new types of bugs and I can't come up with a good usecase for this new feature.

Just trying to imagine what type of issues it could bring:
Entity A has a graph script component which controls it's behavior, and relies on itself having a physics mover
Entity B has A as a prototype, but has removed A' graph script component and added its own. It has also removed the mover and replaced it with a kinematic dynamic body which is controlled by the graph script
Entity C has the kinematic dynamic body of B, but the graph script component of A.

But if a content creator really likes this idea, and you decide to add support for "selecting which prototype", then I would say it ought to be a feature which exists consistently on all types of prototypes (not just entities) and with a good ui/ux to offload the extra mental complexity.

**Comment by niklas-ourmachinery** [comment]
I don't think there are any good reasons for "selecting" the prototype.

Ideally, I think that if an instance has I component A and its prototype P has component A, the instance's component A_i should be an instance of the prototype's component A_p. That is what you would normally expect.

The problem is when A is added to the prototype *after* it has been added to the instance. There are some possible actions:

1. **Disallow it**: In this case, the UI would say "A cannot be added to P, because one of its instances I already has A".
2. **Auto patch the prototypes**. When A is added to P, we find all instances of P that already have A and patch up those instances so that A_p is their prototype.
3. **Allow it**: Allow the add to go through, this means that I will have two A components: A_i and A_p.

I'm not a big fan of (1)... generally I don't like UIs that tell you that you can't do something.

(2) is in my opinion not ideal either, since it will make a lot of changes to object's other than the one you are editing which can be confusing.

If we opt for (3) the question is then how the system should behave when there are multiple components (A_i and A_p) on an entity. I think that:

* The system should act as if the entity only had A_i, since that is the most "local" component.
* The UI should shown a warning symbol next to the A_i component in the UI to indicate that this component has a "weird" prototype chain.
* By right-clicking on this, the user should be able to select to either remove A_p from the instance or reparent A_i to A_p.

**Comment by Tisten** [comment]
I would got for this option:
- When component A_p gets added to P then in A we do a "Remove from This Instance" on A_p since A already have the component A_i.

This is something a user already can do in the reverse order, i.e first create P and add A_p, then instanciate A using P as the prototype, now remove A_p from A and add a new A_i.

This is very similar to doing an override of A_p and _all_ of its properties. The difference is if A_p gets a new property, then this new property will only be added to the lowest prototype and not be overridden. The "Remove from This Instance" option means the new option will be "overridden" right away, so changes to the prototype wont propagate.

**Comment by leonardo-ourmachinery** [comment]
Sorry to both for not explaining myself decently here.

The Three bullet points that Niklas laid out:
- The system should act as if the entity only had A_i, since that is the most "local" component.
- The UI should shown a warning symbol next to the A_i component in the UI to indicate that this component has a "weird" prototype chain.
- By right-clicking on this, the user should be able to select to either remove A_p from the instance or reparent A_i to A_p.
Are currently in master: when this special case happens, the component's name will be shown in red, and there will be an error icon to the left of the component's name.

![image](https://user-images.githubusercontent.com/70660839/168974993-ac392ebb-c293-4219-858a-20cf10a02839.png)

- Reset To Prototype will simply delete the locally added component.
- Propagate Changes to Prototype will simply push the changes to the prototype and remove the locally added component
- Override Will do a "Merge", instantiating the prototype's component and then copying the properties that are different, then will of course remove the dead locally added component.

I tested this with "nested" prototype relations and it seems to be working.

I also made it so that if multiple prototypes had the same component and you "remove from this instance" that component, we will assume that you don't want the entity to have that component, and we won't show any "other" inherited component from another prototype.

---

The only problem with this approach is that when an entity is created there's no guarantee that the "most local" components will be used, as when we do:
```
const tm_tt_id_t *components = tm_the_truth_api->get_subobject_set(tt, asset_obj, TM_TT_PROP__ENTITY__COMPONENTS, ta);
```
we don't know which components should be used, so we simply loop over the components and use the first one of each type.
The alternative would be to "sort" them, but that seems costly.

Considering this, I think @Tisten's idea is valid, even though it means we'll have to expose `private__objects_with_prototype()` (`the_truth.c`) in the public API.

**Comment by leonardo-ourmachinery** [comment]
@Tisten it took 10 minutes to implement your solution and it doesn't have strange corner cases or anything like that... it problably means it's the way to go.

I've also added a "Merge with Locally Removed" option, so the functionalities of this solution are actually on-par with the one currently in master.

The only reason to reject the PR, in my opinion, is if we absolutely don't want to expose `all_objects_with_prototype()` in the truth API.
