### ISSUE TITLE
Renaming an entity doesn't always start with the proper name

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1287]
- **Version:** Git Master Branch
- **OS:** Windows

Repro steps:
1. Open the-machinery.exe with the default project
2. Select the "post_processing_stack" entity in the entity tree tab
3. Press F2 to rename it
4. Note that the string is empty

If you do the same thing for the "sky" entity then the initial string is "sky"

**Comment by niklas-ourmachinery** [comment]
This happens because the Name of the `post_processing_stack` entity is empty.

If an entity does not have a Name set, we still want to display something in the Entity Tree (because an empty entry wouldn't be very useful). For this the rules are:

* If the entity is an instance of an asset, the name of the asset will be displayed.
* Otherwise, "Entity fffffff" will be displayed, where "ffffffff" is a hexadecimal representation of the Entity's ID.

You will notice if you select the `post_processing_stack` entity, that the "Name" field in the Property Editor is also empty.

Given this, I'm not sure if showing an empty string in the situation above is really a "bug", since in fact it doesn't have a name.

We could initialize empty names with the display name at the start of the Rename operation... but that could potentially be a bit confusing, since it would introduce a new entry in the Undo stack.

We could also do something more complicated where the text box is initialized with the display name without actually changing the Name of the entity, but that would require changing some interfaces to support that... not sure if it's worth it for a minor thing like this.

**Comment by Tisten** [comment]
Given this explanation, I better understand the reasoning. That said, I would not have figured that out without the explanation, so I still think this is a UX issue to look into further.

If the "rename" operation would have opened the properties view and made the Name field clearly highlighted then I would have understood that it was empty, but since there is a name in the entity tree and I just want to modify it, it is unintuitive to me as a user that I don't change what I see, but some other hidden property which happened to be empty.

What is the purpose of having nameless things, doesn't that just make it harder to identify them. And is there really a good reason to have both a name and a file name?

I know I question too much here, but good answers might sometimes come by evetually asking the right question...

If something really need two names, and the logic is that if one isn't initialized then it becomes shown as the second, then I would prefer both to be initialized to the same thing at creation time, so none of them are empty. And that all content is patched this way on load time (migration style).

**Comment by niklas-ourmachinery** [comment]
I don't mind the questions at all, I think it's great to question these things. And the whole situation is admittedly confusing, with multiple names and empty names.

**Why are there two different names?**

* Assets need to have a name (to show in the asset browser).
* Not all entities are instantiated from assets... for locally created sub entities, we still want to give them a name so that we can identify them more easily, talk about them, etc.
* Even for entities instantiated from assets we might want to give them a "special name" to specify their role. For example, maybe one of the "tree" instances is "the-special-tree".

**What's the purpose of nameless things?**

* To save memory by avoiding to store a name.
* To automatically reflect changes to the asset name (display name updates when asset name changes).

I don't think either of these is that strong argument. The memory savings would only really matter if you have a lot of mostly empty entities with unique names.

And while reflecting changes to the asset name can be useful... it is kind of confusing that those changes are only reflected if the user *hasn't* given the entity a custom name.

So my current thinking is:

* Anything instantiated from an asset should be given a "local" Name that is the same as the asset name at the time of creation.

* "Empty subentities" should still be given an empty name. (I think having an empty name for these is still preferable to giving them some "randomized" name.)

**Comment by Tisten** [comment]
I think that would be a good improvement from the current state.

I think we should consider how a change would affect https://github.com/OurMachinery/themachinery-public/issues/1251 as well. It can be tricky to reduce confusion, but it is well worth it. Good UX is worth a lot.

**Comment by niklas-ourmachinery** [comment]
Yes, I think it's confusing that there are two different names and multiple ways the name can get set... like when you duplicate an item it gets an auto-enumerated version of the asset name, such as `tree (13)`, but then if you rename the `tree` asset to something else, the name of the instance doesn't get updated. (Maybe you want that and maybe you don't.)

Not 100 % sure how to resolve the inherent mental conflicts in this, because I do think that you want to be able to manually set the name... and I'm also not a big fan of things that happen too automagically... like if you rename the asset and the entity has a name that includes the asset name, we will also rename the entity...

**Comment by leonardo-ourmachinery** [comment]
One possible "painless" solution to the Entity Tree rename problem would be to initialize the rename _buffer_ with the display name, but don't commit anything to TT unless the user press enter.
Basically, it's like the user started renaming and manually typed in the "old" name: at that point he can still decide to abort the operation of commit it, exactly like it happens in a normal rename operation.

**Comment by leonardo-ourmachinery** [comment]
@Tisten @niklas-ourmachinery I pushed this to master:
https://github.com/OurMachinery/themachinery/commit/2327243422ff62ce3ab361c51f199a941879361a

**Comment by Tisten** [comment]
I'm happy with that fix
