### ISSUE TITLE
Hang when aborting the-machinery.exe in cmd.exe 

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1289]
- **Version:** Git Master Branch
- **OS:** Windows

cmd.exe's standard-in hangs saying `More?` and any attempt to get out of it is futile.

It is caused by this line, commenting it out remove the problem:
https://github.com/OurMachinery/themachinery/blob/fb99bbcde0e0d8ecf5457ca45917406d820eb380/the_machinery/host.inl#L91

Also mentioned here:
https://twitter.com/niklasfrykholm/status/1507154065050193923

**Comment by niklas-ourmachinery** [comment]
@simon-ourmachinery Do you have an idea what that line does/is supposed to do? It looks like you added it as part of the CI. Does it cause problems for the CI if you remove it?

**Comment by simon-ourmachinery** [comment]
I will investigate.

**Comment by simon-ourmachinery** [comment]
@Tisten  yes that was imitational since we do not handle input in any way or form currently. The normal build is not inteded to work from the terminal anyways (it wont even work since CTRL + C will not kill the process). As of the research I did it is not possible to get this work when using WindowedApp. How ever for the build server it does not matter since there we compile anyways with `--premake-build-server` which changes it to console app and than the console takes over the process.

When I am going to add the std input handling from the terminal for headless I add this back with a proper solution
