### ISSUE TITLE
Collaboration "changelog" messages bypass the collaboration cache

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1290]
- **Version:** Git Master Branch
- **OS:** Windows

When being connected to collaboration and making changes where buffers are changed, those buffers are sent uncompressed to the server, and from the server to all other connected users, and the buffers avoid the collaborations cache entirely so the buffers get transferred even to users which have them in the cache. And if the author of the change (or any other user which have gotten the buffer) disconnect and reconnect, all new buffers from the last session will be downloaded again.

This changelist transmission code also doesn't respect the TM_FEATURE_FLAG__ON_DEMAND_BUFFER_STREAMING feature flag from https://github.com/OurMachinery/themachinery/pull/921, so all buffers will be transferred to all users, even though all users doesn't need them.

**Comment by niklas-ourmachinery** [comment]
Agreed `tm_tt_serialize_changes_options_t` should have a `serialize_buffers_as_hashes` option, just as `tm_tt_serialize_options_t`.

**Comment by niklas-ourmachinery** [comment]
A fix for this is in https://github.com/OurMachinery/themachinery/pull/967

Please try it out when you have a chance.

This PR does not add on-demand streaming for changelogs, will look into that once this is merged and the regular on-demand streaming is working.

On-demand streaming of changelog buffers add some complexity, because with on-demand streaming of the initial state the host will always have all the buffers. Changelogs can come from other clients, so in this case, if one client asks the host for a buffer from a changelog, the host might not yet have it and may have to ask another client for it before it can respond to the message. (Or potentially, we could make it so that with messages sent to the host, the buffers are never on-demand streamed, so that once the host has a changelog, it is guaranteed to also have all associated buffers.)

**Comment by Tisten** [comment]
Thanks for adding me as a reviewer to that PR, much appreciated.

I will try it out as well today or tomorrow.

It is fine that on-demand streaming isn't fully catered for yet, since it is known to be broken currently anyway.

In regards to the complexity of the "on demand streaming", I would like the server to always be "full state". Only the clients should be allowed to be "on demand". And I would like each client to decide if it should be "full state" or "on demand", the server should not enforce that. I think this will aid when adding support for "controlled host-migration" (https://github.com/OurMachinery/themachinery-public/issues/964) as well. A new "future host" will connect with "full state", and can after that at any point initiate a client redirect and state syncronization with the old host, and when the ownership has been transfered the old host can shut down.

I guess host migration on server crash will require a "client drop and reconnect to new host" type of procedure where all changes which were in flight are lost.

**Comment by niklas-ourmachinery** [comment]
I agree with that... the simplest is to have the host keep full state.

And good point too to have "future hosts" that are ready to take over.
