### ISSUE TITLE
Animation state machine prototyping workflows

### ISSUE THREAD

**Issue by karl-zylinski-ourmachinery** [OurMachinery/themachinery-public#130]
Currently the animation state machine graph does not support the same editing features with regards to prototyping as the "normal graph". We want:
- Possibility to instantiate animation state machine graphs
- 'Remove from instance' with ability to see 'ghosts' of removed nodes and connections.
- 'Add back to instance', which adds back a 'ghost'

**Comment by karl-zylinski-ourmachinery** [comment]
@niklas-ourmachinery I am thinking of looking at this at some point because it could familiarize me with the animation graph. What is the state of this currently? What do you think we need? Is inheritance utilized for ASMs?

**Comment by niklas-ourmachinery** [comment]
It is used in the `animation` sample project... `ybot.asm` inherits from `xbot.asm`... support is so-so... for example, there is "Remove from Instance", but no way of showing the removed nodes in the graph. There is "Add back to instance", but it only works in the Tree View (since the removed nodes aren't shown in the graph).

There's probably a bunch of other little beauty-things that don't work as well as in the regular graph, so it might be worth looking over.

**Comment by karl-zylinski-ourmachinery** [comment]
Thanks. I'll have a look some time soon.

**Comment by niklas-ourmachinery** [comment]
@karl-zylinski-ourmachinery You will take point on disabling the things that are broken, right? I removed myself from the asignees.

**Comment by karl-zylinski-ourmachinery** [comment]
I think this is in an OK shape now. The "illegal" selection where you edit a prototype are not possible anymore and I think being able to add back removed nodes using the tree view is sufficient. It would of course be nice to be able to inspect non-instantiated inherited graphs, but we've tried many attempts at adding such functionality, and until we have the context-systems we've talked about in the entity chat on slack, we can't do much more.
