### ISSUE TITLE
Freeing a nullptr with `CHECK_PTR_SIZES` active causes a `TM_FATAL_ASSERT`

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1306]
- **Version:** Git Master Branch
- **OS:** Windows

I suggest changing this line:
https://github.com/OurMachinery/themachinery/blob/ea20c67a22819be4ec6292e090fdaac623c9a81e/foundation/memory_tracker.c#L195

where it today says `old_size > 0` I think it should say `old_ptr != 0`. A previously allocated 0 byte structure should have returned a null pointer anyway, right?

**Comment by niklas-ourmachinery** [comment]
How exactly do you get this ASSERT?

If I do:

~~~c
tm_free(&app->allocator, NULL, 0);
~~~

I don't get the ASSERT. If I do:

~~~c
tm_free(&app->allocator, NULL, 10);
~~~

I do get the ASSERT, but in this case the ASSERT is correct, because the NULL pointer was *not* allocated with a size of 10 bytes.

(Note this is after my fix to #1307, so potentially things changed with that fix.)

**Comment by Tisten** [comment]
I would claim that the reason the code was written like that was because of copy paste from how it is used in your own code.

Looking at how `tm_free()` is used in the-machinery, I think you ought to patch such code to either an `if(ptr!=0)tm_free();` or `tm_free(a, p, p ? sizeof(p) : 0));`, mostly to set a good example, but also to protect against cases where free was called without alloc, and out of memory cases where 0 bytes were allocated even though you asked for something else.

I agree that not all code need to handle OOM since it is an exceptional state. But there are absolutely sections of code where it is advantagous to do so, where options exist to protect from data loss.

**Comment by niklas-ourmachinery** [comment]
I don't think all `tm_free()` should be converted to that pattern. Rather, I think the programmer needs to keep track of which pointers can potentially be `NULL` and use that pattern for those pointers.

The programmer will have to keep track of that *anyway*, since otherwise they would get an access violation when using the pointer.

(It would be nice with some assistance from the type system here, such as Zigs "optional pointers", but unfortunately C is what it is.)

Handling OOM is kind of a separate topic. If you get a non-fatal assert because of an OOM that's probably the least of your problems :smile:.

**Comment by Tisten** [comment]
Okay.

But at least document the special case of null pointers in tm_free, so it becomes clear that it differs from C's `free()` in that null pointers are not a no-op, and thus need special care with the size argument.

**Comment by niklas-ourmachinery** [comment]
Done
