### ISSUE TITLE
Entity tree logic for drag and drop is complex and confusing

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1323]
- **Version:** Git Master Branch
- **OS:** Windows

Sorry for the subjective description, based on personal opinion.

Some specific issues:
* When dragging a single object, this is handled by the three cases "entity", "component" or "asset" but when dragging multiple objects there is a different logic called "selection" which seems to assume that all objects are entities
* When dragging a single asset, the code has yet different logic for the asset object than the "entity", "component" or "selection"
* When dragging multiple assets, they will be represented by a single `asset_browser` object which will be instantly denied by the entity tree since it isn't of any of the "entity", "component" or "asset" kinds.

I have asked @leonardo-ourmachinery a bunch of questions about this already, so he has an idea about what to do about it.

**Comment by leonardo-ourmachinery** [comment]
I restructured the drag and dropping code of the entity tree tab a bit here:
https://github.com/OurMachinery/themachinery/commit/dc5aa3b46527dd90a17dd943c459e6db52dca637

Now the only function responsible for drag and dropping interactions is `drag_interact_with_entity()`, and it now handles any number of entities/components/assets passed.

I also modified the asset browser to pass the "correct" asset instead of the asset browser object when there are multiple assets being dragged around.

**Comment by Tisten** [comment]
Yes, much better now. Both code structure and functionality is improved.
Thanks
