### ISSUE TITLE
show graph properties in the inspector (properties)

### ISSUE THREAD

**Issue by laurentopia** [OurMachinery/themachinery-public#133]
everything is a graph is powerful, for gameplay or level designer it would be beneficial to "float" properties from deep inside the graph to the inspector

**Comment by niklas-ourmachinery** [comment]
Not 100 % sure what you mean here... could you provide a sketch or an example?

**Comment by laurentopia** [comment]
![image](https://user-images.githubusercontent.com/26075468/77210787-10b7cc00-6abf-11ea-9762-9feabd7ca9b1.png)

**Comment by niklas-ourmachinery** [comment]
Hmm... so you mean like an indirection step for the Properties window.

You would drag out properties that you want in the properties window into a "holding area" so that when you select that holding area, those properties would be displayed in the Properties window.

And the purpose would be to provide a simplified abstraction of the graph. A less experience user would not have to care about the whole graph... just the properties in the "holding area".

I see where you are going with this and I think we want something like this, but not done exactly in this way. I think would we want to do instead is to allow entire networks of nodes to be "collapsed" to a single node. That single node would expose the "public properties" of the network.

So for a gameplay programmer or designer, you would just give them this "collapsed" node and it would have all the public properties that they should be able to change.
