### ISSUE TITLE
Blackboard entry ``TM_ENTITY_BB__UI_VIEWPORT_RECT`` returns null ptr after restarting the simulation

### ISSUE THREAD

**Issue by julhe** [OurMachinery/themachinery-public#1343]
- **Version:** Git Master Branch (270bf840cb88be61d24826f66f548950c3d45d6d)
- **OS:** Windows

Uppon restarting the simulation,
 ``` C
const tm_rect_t viewport_rect = *(tm_rect_t *)tm_entity_api->get_blackboard_ptr(entity_ctx, TM_ENTITY_BB__UI_VIEWPORT_RECT);
``` 
in scene_common.c:823 triggered  ``Access violation reading location 0x0000000000000000``.

I don't have a repro case, but I found it concerning that the blackboard returns null pointers for "built-in" entries.
Dump: [the_machinery_exe 2022-05-25 18.30.56.zip](https://github.com/OurMachinery/themachinery-public/files/8773233/the_machinery_exe.2022-05-25.18.30.56.zip)

**Comment by julhe** [comment]
Okay, it seems easy to reproduce: just keep the camera settings panel open and restart the simulation.

**Comment by leonardo-ourmachinery** [comment]
Fixed in master.

And yes, I agree. I think that there should at least be some way for users to know which Blackboard pointers can potentially be NULL and which are instead guaranteed to be valid. I've left a TODO in the code. (We'll planning on revisiting the blackboard system in the not-so-distant future anyway).
