### ISSUE TITLE
Simulation entry state is null, after using persistent entities in simulation tab

### ISSUE THREAD

**Issue by julhe** [OurMachinery/themachinery-public#1344]
- **Version:** Git Master Branch(7b982bb2d1e59ac65c8bc5c3b06c868baf6d3f34)
- **OS:** Windows

To reproduce:
1. Build the test plugin
2. Load the project
3. Start the simulation of world.entitiy
4. Save & restore the persistent entities 
![grafik](https://user-images.githubusercontent.com/18037091/170468025-40a890fd-de5d-4738-baf6-b0bf0811449e.png)
5. Observe that the assertion in the test plugin is triggerd, as the pointer to the state has become null.

Repro project: [machinery_persistent_entities_and_sim_entry_plugin.zip](https://github.com/OurMachinery/themachinery-public/files/8778185/machinery_persistent_entities_and_sim_entry_plugin.zip)

**Comment by leonardo-ourmachinery** [comment]
Fixed in master with https://github.com/OurMachinery/themachinery/commit/ba007fc7eae338e5ab22b50e442cc20147f239af.

@simon-ourmachinery  FYI: The problem was that Simulation Entry systems weren't actually removed from the ECS when `clear_world()` is called, as the remove system commands were thrown away and not executed. I simply added a "flush_command_queue()` call inside `clear_world()`.
