### ISSUE TITLE
Can't convert "Mixer Is Alive" entity graph node to a "Mixer Is Paused" node

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1354]
- **Version:** Git Master Branch
- **OS:** Windows

Repro project:
[ConvertNode.zip](https://github.com/OurMachinery/themachinery-public/files/8785506/ConvertNode.zip)

Open the project above, and the entity graph in entity "world". Right click on the "Mixer Is Alive" node and choose "Convert Node". Note that "Mixer Is Alive" is the only node type you can convert to. I would at least expect "Mixer Is Paused" to appear, but I would ***NOT*** expect "Mixer Is Alive" to appear since that is the node type which is already used.

**Comment by leonardo-ourmachinery** [comment]
I've pushed in master a fix so that you can't convert to the "same node".

The other part is a bit more complicated to fix, as to match "by type" we need some heuristic to determine "which" connection to match when there are multiple of the same types. Maybe we should consider a connection compatible if either it has the same name OR it has the same type _and_ it's at the same index.

I'll think a bit more about this.

**Comment by Tisten** [comment]
I can't say I understand the complexity.
Pause and stop seems 100% identical to me:
```
static tm_graph_component_node_type_i mixer_pause_node = {
    .static_connectors.in = {
        { "", TM_TT_TYPE_HASH__GRAPH_EVENT },
        { "playing", TYPE_HASH__PLAYING_SOUND },
    },
    .static_connectors.out = {
        { "", TM_TT_TYPE_HASH__GRAPH_EVENT },
    },
```	
and
```
static tm_graph_component_node_type_i mixer_stop_node = {
    .static_connectors.in = {
        { "", TM_TT_TYPE_HASH__GRAPH_EVENT },
        { "playing", TYPE_HASH__PLAYING_SOUND },
    },
    .static_connectors.out = {
        { "", TM_TT_TYPE_HASH__GRAPH_EVENT },
    },
```
I guess I need to find the code which does the matching to grasp it.

**Comment by Tisten** [comment]
Okay, thanks for thinking about this. :)

I usually solve the simple cases first, and leave the more complex cases disabled. And then I solve slightly more complex cases when I have a better understanding of which cases I want/need to cover.

So that's why I fail to understand why the algorithm works in any situation at all if it doesn't work for the simplest case...

But I haven't looked deeper into this specific problem, so I should stop ranting.

**Comment by leonardo-ourmachinery** [comment]
I improved the matching algorithm so that when there's not a match "by name", it will look and see if there's a connection by "index and type". (Which covers this specific case too)

@Tisten here's the commit: https://github.com/OurMachinery/themachinery/commit/eb3c7d487fb2bd823ddf086fb6b1159478e3270c
I didn't explained myself very well, but please feel free to ping me on Discord if you wanna discuss more about it.
