### ISSUE TITLE
ESC in simulation to release input

### ISSUE THREAD

**Issue by laurentopia** [OurMachinery/themachinery-public#136]
simulate window separate from scene window is powerful in that you can edit the scene but when in the simulate window input cannot be released to perform editor functions

**Comment by niklas-ourmachinery** [comment]
I see what you mean. It's a bit disconcerting when you move the mouse to click something in the UI and the simulation camera swivels around. Having a way to explicitly connect/disconnect input from the simulation tab seems like a great idea.

**Comment by laurentopia** [comment]
I didn't think about explicit connection to the input but yeah why not have click on the tab or in the simulate window be that connection, and consume that click so the character doesn't shoot a bullet.

**Comment by karl-zylinski-ourmachinery** [comment]
@niklas-ourmachinery In our current samples we let the gameplay code capture input if they need it. You can even make sure to not swivel camera etc when there is no captured input. I think this is the right way forward since it is flexible and not magical.

**Comment by niklas-ourmachinery** [comment]
:+1: 

Agree... I think we should fix this in all samples for the 2021.12 release.

**Comment by karl-zylinski-ourmachinery** [comment]
Ok. I'll do it for that release.

**Comment by karl-zylinski-ourmachinery** [comment]
I have now added moues capture to the animation sample. This does the capturing using the entity graph. When there is no capture, no input is processed in the sample. For the other gameplay samples we already have moues capture, and those give an example of how to do it from C code rather than the graph.

Available now in master branch or in upcoming 2022.1 release.
