### ISSUE TITLE
Autobuilder issue: Build fails from other person's errors

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1419]
- **Version:** Git Master Branch
- **OS:** Windows

I thought the autobuilder would preflight incoming changes and back them out if they contained build errors @simon-ourmachinery. Now I am getting build errors from an earlier commit @leonardo-ourmachinery:
![image](https://user-images.githubusercontent.com/6726075/175024658-063e4573-bb87-4061-95d4-f690473d8490.png)

**Comment by simon-ourmachinery** [comment]
GitHub Actions run after a commit hence if the commit is broken my team mates will get the notification. This is a design decison we have made since we are not using the PR workflow. This means there is nothing I can do if you rebase/merge to a unstable master in between fixes its upto the user to work against a unstable masters.
