### ISSUE TITLE
New mail spam when creating Pull Requests

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1426]
- **Version:** Git Master Branch
- **OS:** Windows

Yesterday a lot was fixed on this front, my PRs started to get green and I didn't get spammed anymore.

Today I started getting this:
<img width="473" alt="image" src="https://user-images.githubusercontent.com/6726075/175308570-140264af-9daf-4b92-b69f-7b01c86385c3.png">

**Comment by simon-ourmachinery** [comment]
Thanks if reporting issues about the Action related issue please read the workflow error message and post them. You find them under PR -> Checks -> Select the ones that fail -> Summary.

Example output:
```
[Invalid workflow file: .github/workflows/linux_build_pr_full.yaml#L138](https://github.com/OurMachinery/themachinery/actions/runs/2549370774/workflow)
The workflow is not valid. .github/workflows/linux_build_pr_full.yaml (Line: 138, Col: 11): The identifier 'tmbuild' may not be used more than once within the same scope.
``` 
 It is a normal reaction from GitHub to report the failure of GitHub Actions since this is your notification setup. If you do not like geting emails as a PR user check: https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications
 
Keep in mind that if one does this you will not know if your PR was successfully built unless you check the action periodically.  Only employees get a slack notification.
