### ISSUE TITLE
Framing on a scaled dcc asset will incorrectly place the camera

### ISSUE THREAD

**Issue by chrisperrella** [OurMachinery/themachinery-public#162]
In `frame_bug.the_machinery`, framing on a scaled `plane.dcc_asset` will move the camera to an incorrect position. 

Note:
This appears to have something to do with the `.dcc_asset`'s `pPlane1_$AssimpFbx$_Scaling` node being set to `0.01`

Repro:
- Open `scene.entity`  
- Navigate to `plane.entity` in the Entity Tree (asset is scaled x100)
- Press `F` on the keyboard
- Observe the camera snap to an incorrect location

![frame_bug](https://user-images.githubusercontent.com/8780192/77241142-6ec1dd80-6bab-11ea-9da6-41e500c1acb9.jpg)

https://www.dropbox.com/s/dsk7pm8uqv7d0pc/frame_bug.zip?dl=0

**Comment by niklas-ourmachinery** [comment]
The assets bounding box is set to `{{-50,0,-50}, {50,0,50}}` when it should really be `{-0.5,0,-0.5},{0.5,0,0.5}`. That's why when the camera tries to frame the asset it gets far far away.

As you say, I think it has to do with the asset having scaling in it. Seems like the bounding box is not scaled with the `0.01` scale that the rest of the entity is scaled with.

@tobias-ourmachinery This is more your domain. Can you look into this?
