### ISSUE TITLE
SUGGESTION: context menu to open the C code for a plugin

### ISSUE THREAD

**Issue by laurentopia** [OurMachinery/themachinery-public#165]
Like Edit Graph but for plugin, when you right click edit it'll open your favourite editor.

**Comment by niklas-ourmachinery** [comment]
This would be doable for plugins that are compiled locally on your machine, because we could read the source code path from the .pdb.

However, if you are using a plugin compiled by someone else (which I think will often be true), the .pdb will point to the source code path to the plugin on *there* machine. So it won't work.

Not sure if we should have this option when there are a lot of cases where it wouldn't work. (Even if I can see it would still be useful in the cases where it would work.)

**Comment by laurentopia** [comment]
In a team environment I think you're right, the plugin source won't be available locally.
But as it is currently, collaboration tab only works with a local server so >edit could return the local path on his machine and since you already have to resolve some of that for networking, maybe you can also resolve the absolute network path name instead of local path, or use collab as a pass through to transfer the source file to the one who pressed >edit

**Comment by niklas-ourmachinery** [comment]
But there is no guarantee that the host built the plugin either, it might be downloaded from the internet. In my opinion this is too much complexity for too little added value.
