### ISSUE TITLE
GUI: double click an entity in the entity tree to open the entity

### ISSUE THREAD

**Issue by laurentopia** [OurMachinery/themachinery-public#166]
or even better allow to edit the entity directly and flag it with a special icon as having an override

**Comment by niklas-ourmachinery** [comment]
You mean open the prototype in the case where an entity was instanced from a prototype, right?

A bit unsure about what you mean by "edit the entity directly".

Do you mean like you would go into a "special mode", where you would edit the prototype instead of the instance, but it would be shown in the context of the current scene.

Basically, what you would get by editing the instance and then selecting "Propagate Changes to Prototype", but without the hassle of having to override every singe thing in order to edit it?

**Comment by laurentopia** [comment]
> Do you mean like you would go into a "special mode", where you would edit the prototype instead of the instance, but it would be shown in the context of the current scene.
> 
> Basically, what you would get by editing the instance and then selecting "Propagate Changes to Prototype", but without the hassle of having to override every singe thing in order to edit it?

yes

**Comment by niklas-ourmachinery** [comment]
Sounds convenient, but I think it might be a really tricky feature to add. Need to think more about this.

**Comment by niklas-ourmachinery** [comment]
Fixed double click.

Editing-in-place is more complex... might consider that for later.

**Comment by laurentopia** [comment]
I must say I'm impressed how fast you implement stuff in Machinery.
