### ISSUE TITLE
Updating of core assets resets instance overrides.

### ISSUE THREAD

**Issue by tobias-ourmachinery** [OurMachinery/themachinery-public#190]
After replacing the `core/light.entity` with an asset from the core project (and bumping its version number) we appear to be loosing all instance overrides in the upgrade process if opening an old project.

**Comment by karl-ourmachinery** [comment]
Fixed. The old `core/light.entity`, which was created in code, has been replaced with an entity from the core project. Since all the internal UUIDs changed when we did this, the old old was deprecated. The old one will still live on in the user's project, with the name `core/light (deprecated).entity`.
