### ISSUE TITLE
Support depth test for primitives in `tm_primitive_drawer_api`

### ISSUE THREAD

**Issue by khskarl** [OurMachinery/themachinery-public#199]
Currently all primitives are drawn by `tm_primitive_drawer_api` without depth testing, yet there are situations in which depth testing is desirable, for example: ![image](https://user-images.githubusercontent.com/13659144/79808271-b6bb5800-8343-11ea-92f3-72ccd880cd1d.png)

As in this image, supporting depth test would be valuable for making the depth of the line clearer, and using such primitives for debugging can easily get cluttered and confusing.

**Comment by frank-ourmachinery** [comment]
Currently all primitives are drawn in a single draw call. to change it globally you can change the depth_test_enable setting in the primitive_drawer.shader file. I think we can split this up into two draw calls, one with and one without depth testing. There might however be other settings that we'd like to be changeable then, like instead of additive blending we might want a simple override. Not sure what the best way to approach this is.
