### ISSUE TITLE
tmbuild.exe fails to run on samples

### ISSUE THREAD

**Issue by peterlindgren** [OurMachinery/themachinery-public#205]
> C:\Users\Peter Lindgren\work\themachinery\samples>..\bin\tmbuild.exe
Installing 7za.exe...
> '"C:\Users\Peter Lindgren\work\themachinery\samples\lib\premake-5.0.0-alpha14-windows\premake5"' is not recognized as an internal or external command,
operable program or batch file.
> tmbuild: could not run `"C:\Users\Peter Lindgren\work\themachinery\samples\lib\premake-5.0.0-alpha14-windows\premake5" --file=premake5.lua "vs2019" ""`

**Comment by niklas-ourmachinery** [comment]
Hmm... weird I'm trying to reproduce the issue here, but I'm not able to.

* I suspected that it might be the space in your path causing problems, but it seems to work for me even with a space in the path.
* Can you verify that you have the file `C:\Users\Peter Lindgren\work\themachinery\samples\lib\premake-5.0.0-alpha14-windows\premake5.exe`?
* What happens if you try to run the premake command yourself from the command line?

```
"C:\Users\Peter Lindgren\work\themachinery\samples\lib\premake-5.0.0-alpha14-windows\premake5" --file=premake5.lua "vs2019" ""
```

* What if you run the same thing but write `premake5.exe` instead of `premake5`?

**Comment by peterlindgren** [comment]
I was unable to reproduce it today unfortunately.

**Comment by niklas-ourmachinery** [comment]
Ok, closing this for now. Reopen if you can find a repro case.
