### ISSUE TITLE
Ability to Scale Editor UI

### ISSUE THREAD

**Issue by ssoher** [OurMachinery/themachinery-public#208]
I don't use high dpi scaling on a 4k monitor due to various reasons. Some applications like Blender and Godot have a custom UI scaling feature (see attachment) and it works amazingly well without effecting OS level scaling. Would something like this be possible for the Machinery?

![blender_uiscale](https://user-images.githubusercontent.com/4283979/80678490-a7ff3e80-8ac3-11ea-950e-4e7da4b1f7e0.gif)

**Comment by niklas-ourmachinery** [comment]
This should definitely be possible... we already have a scaling factor that we use to switch between high/low DPI situations. It is just a matter of exposing a UI for it and make sure it's piped in everywhere.

It think what we would want to expose is a multiplier on the system scaling factor, so that things still behave reasonably if you drag windows between monitors, etc.

**Comment by ssoher** [comment]
@niklas-ourmachinery Any updates on this?

**Comment by niklas-ourmachinery** [comment]
No, but we're considering this for a future version.

**Comment by tobias-ourmachinery** [comment]
Next version will allow you to set a user defined resolution scale from the application settings.
