### ISSUE TITLE
Norton flags all dlls as unsafe and removes them

### ISSUE THREAD

**Issue by PixelRifts** [OurMachinery/themachinery-public#225]
I downloaded the latest version of our machinery i.e. 2020.4, All the dlls seem to have a medium threat level

**Comment by niklas-ourmachinery** [comment]
Does Norton provide any reason why it considers the DLLs "medium threat"? There should be nothing bad in our DLLs and without knowing exactly why Norton flags them, there is not much we can do about it. What if you build your own DLL from `samples/plugins`, does Norton flag that too?

I have pretty bad experiences with anti-virus software in general (flagging perfectly fine stuff as "threats", slowing down network traffic to a crawl by inspecting all packages, etc), so I'm not that keen on spending a lot of time and effort on trying to please Norton. But if you can pinpoint what the problem is and it's an easy fix -- sure.

The only anti-virus software we really consider is Windows Defender (since it is default installed) and it gives us a pass:

![image](https://user-images.githubusercontent.com/26548514/82081560-62ce3580-969b-11ea-836d-5898702f7be2.png)

**Comment by PixelRifts** [comment]
When I scanned it again, it showed no threat. But when it auto scanned, It quarantined all the dlls. It was just annoying to click on every dll report and restoring it. IDK why it happened. I know all the dlls are safe. 👍 :)
