### ISSUE TITLE
No localization entries for the new Scene View options 

### ISSUE THREAD

**Issue by philipstenmark** [OurMachinery/themachinery-public#228]
The newer scene view options (pivot, snapping, lighting environment, simulate shortcut...) has no localization entries for `Swedish`. When the language is changed, multiple errors are shown.

I don't know how favored the language feature is yet or if there are more languages on the way, so this is very minor.

**Comment by niklas-ourmachinery** [comment]
We mostly just have localization for Swedish there so that we can test that the localization system is working (and because it is the language it is easiest for us to translate to). Having Swedish translations is not *really* a priority. 😄 

Everything in the UI is supposed to be translated, but sometimes we forget to do a localization pass and updating the localization tables.

I've made a pass now and everything should be translated for the next release (probably 2020.5.a).
