### ISSUE TITLE
Maximizing editor window causes unwanted behavior

### ISSUE THREAD

**Issue by cyberfrank** [OurMachinery/themachinery-public#233]
As known, on the initial `the-machinery` startup, the editor window is _seemingly_ maximized (not fullscreen). However, when pressing the maximize button at this point, the window gets resized and starts to cover the taskbar (which is not the effect of "maximize" in terms of Microsoft Windows). 

Also, when dragging the title bar to move the window around, the window sometimes enters this accidental "fullscreen" mode as well. As a result of this, the window can begin to offset and mouse position and result in inaccurate window focus. When attempting to manually drag and resize the window after this, it can sometimes turn black and stop to render in some areas.

I use the word _sometimes_ a lot here since the glitches that occur are unpredictable. Further testing and documentation is needed for exact steps. I can provide video footage of the faults later if needed.

Note that the issue only occurs when the window fully covers the screen (as it does when the editor launches). However, when the editor window is manually resized to be smaller than the native screen size, maximizing works as expected.

**Comment by tobias-ourmachinery** [comment]
I assume you're running on monitor with native resolution of 1920x1080? That would explain why I haven't seen this as all of my monitors runs at a higher resolution.

We'll try to come up with a fix for next release, however as mentioned in this issue: #187 I still haven't found a fully reliable way to detect when Windows thinks the application is in "fullscreen", i.e covering the taskbar. Maybe we should just assume that a window that has the exact same size as native resolution of display hosting the window should be considered being in fullscreen, and when in fullscreen don't allow moving the window..

**Comment by leonardo-ourmachinery** [comment]
I made it so that now we use CW_USEDEFAULT when we "don't know" or how big the window should be.
So now at startup we create the window passing CW_USEDEFAULT and _then_ we maximize it.

I tested this a bit on the following and I couldn't see anything weird:
1) monitor display resolution of 1920 x 1080, no dpi scaling
2) monitor display resolution of 4k, dpi scaling at 150%
3) monitor display resolution of 4k, no dpi scaling

I don't think there's much we can do about the black bands that appear when resizing/maximizing the window, so I'm closing the issue for now.
