### ISSUE TITLE
Entity context creation with TM_ENTITY_CREATE_COMPONENTS_ALL

### ISSUE THREAD

**Issue by celifan** [OurMachinery/themachinery-public#239]
Creating a new entity context  just after the Initialize and setup the truth in  simple_3d.c create_application() by adding  :

 app->entity_context = tm_entity_api->create_context(&app->allocator, app->tt, TM_ENTITY_CREATE_COMPONENTS_ALL);

triggers : 
Exception thrown at 0x00007FFFD27C92CB (tm_dcc_asset.dll) in simple-3d.exe: 0xC0000005: Access violation reading location 0x0000000000000000. occurred

requiring a "naked context" is fine 
app->entity_context = tm_entity_api->create_context(&app->allocator, app->tt, TM_ENTITY_CREATE_COMPONENTS_NONE);

**Comment by niklas-ourmachinery** [comment]
Thank you for reporting it.

The problem was that some components were dependent on system that is not created by the Simple3D app (render backend and shader repository). I've fixed this for the next release.

Can you wait until the next release (mid-June) for the fix or do you need a hotfix for this issue?
