### ISSUE TITLE
Error message when reloading first-person or third-person sample project

### ISSUE THREAD

**Issue by ExoVerse** [OurMachinery/themachinery-public#257]
You closed this problem too soon. It's still not resolved.
Previous Ticket : https://github.com/OurMachinery/themachinery-public/issues/246

Same problem with 2020.6.

To reproduce it, click play, then click pause, then click that reset button that I am circling in the picture. You will see the error messages. EDIT ( Two of the Samples have this problem. The rest of them seems to have fixed themselves. )

![results](https://user-images.githubusercontent.com/66333818/85214148-7c673a80-b335-11ea-8fa5-2853602f4e7b.png)

**Comment by InjaEm** [comment]
Took another screen shot of another sample.

![results2](https://user-images.githubusercontent.com/66333818/85214288-cc92cc80-b336-11ea-8e20-66998ec3d2dc.png)

**Comment by niklas-ourmachinery** [comment]
I'm unable to reproduce this. Are you running both the latest code (2020.6) and the latest version of the sample projects (2020.6) when you get this error?

**Comment by InjaEm** [comment]
It's the latest versions, Samples and Program. Even the picture shows it to be the latest.

**Comment by Arazu161** [comment]
I only tested the first and third person samples, but I also get these errors.

**Comment by InjaEm** [comment]
What I'm curious about is why it's calling a folder that doesn't exist on my computer.

**Comment by Arazu161** [comment]
I think that is just a quirk of the logging system and the locations are where the files are on Niklas' computer. I've noticed it before with something else (can't remember what exactly now)

**Comment by niklas-ourmachinery** [comment]
Yes, these are internal error message... so they tell us where in the source code it is happening. Since you don't have the source code on your machine, it can't refer to any path on your machine... but we should mayb estrip the `C:\work\themachinery` part from these error messages to make it less confusing.

**Comment by niklas-ourmachinery** [comment]
Managed to reproduce this by downloading the latest beta... for some reason I couldn't reproduce it in trunk head... will investigate.

**Comment by niklas-ourmachinery** [comment]
For my own reference, these are the errors I get when reloading the first person project:

```
✖ C:\work\themachinery\plugins\gameplay\gameplay.c(56): error leaked 1 allocations 56 bytes
✖ C:\work\sample-projects\plugins\gameplay\first_person\gameplay_sample_first_person_component.c(373): error leaked 1 allocations 440 bytes
✖ C:\work\themachinery\foundation\memory_tracker.c(120): error: Allocation scope `gameplay_sample_first_person_component` has allocations
```

**Comment by niklas-ourmachinery** [comment]
@karl-ourmachinery Have a look at this... I think you fixed it before so I'm not sure why it's still happening.

Also confused why it seems to happen in the release, but not in trunk.

**Comment by karl-ourmachinery** [comment]
This happens because we have renamed the component that contains the first person gameplay code. You may have ended up with two dlls in the plugins folder, one named `tm_first_person.dll` and another named `tm_gameplay_sample_first_person_component.dll`. Only `tm_gameplay_sample_first_person_component.dll` should exist. If both do, then we get a conflict in the plugin system and we can get the weird errors above.

We'll make sure that these duplicates don't end up in the next release.
