### ISSUE TITLE
Reading buffer data with const tm_the_truth_o

### ISSUE THREAD

**Issue by peterlindgren** [OurMachinery/themachinery-public#294]
Hi,

I noticed that const_buffers were removed from tm_the_truth_api in the May 2020 update. I’ve been using it in my tm_component_i load_asset callbacks.

`const struct tm_buffers_i *(*const_buffers)(const tm_the_truth_o *tt);`

`void component__load_asset(tm_component_manager_o *manager, tm_entity_t e, struct tm_custom_component_t *c, const tm_the_truth_o *tt, uint64_t asset);`

How do I read buffer data with `const tm_the_truth_o *` now that the const_buffers function is removed?

Thanks,
Peter

**Comment by niklas-ourmachinery** [comment]
Hi,

the `const_buffers()` call was removed because `tm_the_truth_api->get_buffer()` was changed to return a `tm_tt_buffer_t` with the buffer content. Since you have all the buffer content in the return value from `get_buffer()` you typically don't need the `tm_buffers_i` pointer anymore, which is why we removed the call (we weren't using it anywhere in our code anymore).

Do you still need the `const tm_buffers_i *` for anything, or do you have all the data you need in the `tm_tt_buffer_t` struct?

**Comment by niklas-ourmachinery** [comment]
For reference: `const_buffers()` was removed in this commit: https://github.com/OurMachinery/themachinery/commit/d19a1a240.

**Comment by peterlindgren** [comment]
That should do it, thanks!
