### ISSUE TITLE
Crash when adding tesselated plane component

### ISSUE THREAD

**Issue by DerTee** [OurMachinery/themachinery-public#298]
TM-Beta-Version: 2020.9

When adding a tesselated plane component to a fresh, empty entity in the editor, the editor froze and crashed after a second or so.

Steps to reproduce:
1. New project
2. New Entity
3. Add component "Tesselated Plane" -> Crash

> Dump Info:
> Exception Code: 0xC0000005
> Exception Information:  The thread tried to read from or write to a virtual address for which it does not have the appropriate access.

Beware: I'm a new user and this was the first time I tried out The Machinery! Also my anti virus software (Avast Free AV) reported the executables of TM as "rare and suspicious" so I added exceptions for them since I assumed it was because the executables are unsigned.

**Comment by niklas-ourmachinery** [comment]
I wasn't able to reproduce this.

Do you have the latest GPU drivers installed?

Can you send us your log from `AppData\Local\The Machinery\Logs` and also any crash dumps you get (might be in the same folder as The Machinery or in `AppData\Local\The Machinery\CrashDumps`. You might need to run `utils/enable-full-dumps.reg` to turn on dump generation, but if it froze for a second, it sounds like crash dumps are already being generated (that's the freeze).

Yes, anti-virus alert is to be expected... we should maybe look into signing the executables.

**Comment by frank-ourmachinery** [comment]
I get the crash as well, it's more general than the just for the Tessellation Component. You need to use the "Add Component" button in the Properties Tab and not the "Add Component" item in the right click context menu in the Entity Tree view. It's caused by a mismatch in the item selected by the user and the item selected by the properties tab causing a null item to be selected and somewhere on the line the UI crashes on a null string.

**Comment by frank-ourmachinery** [comment]
Just fixed it, might need a hotfix release as most new people use the add component in the property tab (I certainly do) instead of the context menu option in the entity tree.
