### ISSUE TITLE
Use scroll weel to zoom in/out in "Device memory analyzer"

### ISSUE THREAD

**Issue by d44m1n** [OurMachinery/themachinery-public#32]
Using scroll to zoom-in / zoom-out will be more intuitive than alt + rmb in "Device memory analyzer".

As in title. 
I took me some time to find out how to do this :P

**Comment by niklas-ourmachinery** [comment]
Agreed, we should support scroll wheel too, since it is not used for anything else in this tab.

Modifier key + mouse button actions are not very discoverable. I think it would help to have some kind of help text for them. For example, while the modifier key is being held, the status bar could display what the different mouse buttons would do. I think I've seen this in some other applications (maybe Blender?).

**Comment by d44m1n** [comment]
I personally don't mind combinations like `modifier key + mouse button ` as long there are shortcuts settings. 
Then when I need something, I can just find it.

Another option could be help button?
After clicking on the help button you will get brief description about tab, with link to documentation where is more detailed description.

Yup, blender have this.

**Comment by niklas-ourmachinery** [comment]
Actually, using the scroll wheel here doesn't work very well, because if you make the tab smaller a scrollbar will appear, and we want the scroll wheel to work with that scrollbar rather than zoom in the view. Closing this issue.

I made a separate issue for showing help text for mouse actions:

https://github.com/OurMachinery/themachinery-public/issues/53
