### ISSUE TITLE
Gizmos broken in some projects

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#325]
- Open pong sample
- Select any floor tile
- The gizmo will be at the origin (incorrect)
- Using the move gizmo will zero out all transform members

**Comment by frank-ourmachinery** [comment]
I can't reproduce the issue, gizmos work fine in both world and local space.
![image](https://user-images.githubusercontent.com/70658773/96979377-605fe980-151f-11eb-9bd6-a57f8ab95d84.png)
Some of the wall segments have a weird gizmo location, but that is because they are exported to work with the grid I think.
![image](https://user-images.githubusercontent.com/70658773/96981128-d6645080-151f-11eb-8dcc-df60355a6264.png)

Possibly just needs a clean build?
