### ISSUE TITLE
Fatal Error opening the-machinery.exe (Vulkan error)

### ISSUE THREAD

**Issue by jfaz1** [OurMachinery/themachinery-public#341]
I'm trying to open the machinery for the first time to no avail. I'm on a GTX 1070, I have latest drivers. Tried installing new drivers and rebooted, same thing.

![image](https://user-images.githubusercontent.com/25165780/97652923-54ec5100-1a3e-11eb-9a6d-4873958df83e.png)
Log:
```
The Machinery - Version 2020.10
Minimal plugin loaded.
Number of available instance layers: 8
    VK_LAYER_NV_optimus (Description: NVIDIA Optimus layer)
    GalaxyOverlayVkLayer (Description: Galaxy Overlay Vulkan Layer)
    GalaxyOverlayVkLayer_VERBOSE (Description: Galaxy Overlay Vulkan Layer)
    GalaxyOverlayVkLayer_DEBUG (Description: Galaxy Overlay Vulkan Layer)
    VK_LAYER_NV_nsight (Description: NVIDIA Nsight Visual Studio Edition interception layer)
    VK_LAYER_bandicam_helper (Description: Vulkan Bandicam Helper)
    VK_LAYER_VALVE_steam_overlay (Description: Steam Overlay Layer)
    VK_LAYER_VALVE_steam_fossilize (Description: Steam Pipeline Caching Layer)

Number of available instance extensions: 2
    VK_EXT_debug_report
    VK_EXT_debug_utils

C:\work\themachinery\plugins\vulkan_render_backend\vulkan_render_backend.c(2476): error: vkCreateInstance(): -9
C:\work\themachinery\the_machinery\the_machinery.c(6015): error: setup_render_backend(app, (setup_render_backend_t){ .vulkan_validation_layer = vulkan_validation_layer, .adapter_request = adapter_request })
```

**Comment by frank-ourmachinery** [comment]
Thank you for checking out The Machinery, the error you are getting (-9) says that your driver is incompatible. Currently The Machinery required Vulkan version 1.1.82, it seems like this isn't supported by your driver.  What is the driver version you are running?

**Comment by jfaz1** [comment]
Thanks for the reply! How do I check my vulkan version? I'm on nvidia
457.09.

**Comment by tobias-ourmachinery** [comment]
Should work just fine on GTX 1070 with 457.09, hmm. I suspect something might be broken with you driver installation. Can you run other Vulkan applications / games on your machine?

Maybe try uninstalling the driver completely and then reinstalling it.

**Comment by jfaz1** [comment]
Other vulkan applications work fine, I tried running rainbow six siege and dolphin emulator on Vulkan with no issues. I used DDU and uninstalled/reinstalled my drivers and unfortunately same issue. Anything else I could try?

**Comment by jfaz1** [comment]
Alright I rank VulkanInfo and it says my version is 1.2.141.
Here's the full log: https://pastebin.com/6XQUcWbU

**Comment by frank-ourmachinery** [comment]
I've noticed from your full log that some of the layers are for a Vulkan version a few patch layers below our required version. If those are enabled by default then you could try disabling those. You'll have to go into the Windows registry and delete the layers that have a version below 1.1.82. Other than that, I have absolutely no clue what could be causing this.

Steps for removing automatic layers:
1. Open Windows registry (regedit)
2. Go to HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers
3. Remove the entries (file paths) to the layers that have a version less than 1.1.82.

Layers that you have that might be causing issues:
- GalaxyOverlayVkLayer 
- GalaxyOverlayVkLayer_DEBUG 
- GalaxyOverlayVkLayer_VERBOSE 
- VK_LAYER_EOS_Overlay 
- VK_LAYER_EOS_Overlay 
- VK_LAYER_NV_nsight 

It would be pretty annoying if this works, because that would mean that other slightly outdated applications would interfere with Vulkan startup if we don't explicitly handle them.

**Comment by jfaz1** [comment]
Thanks for the in-depth response. I managed to get rid of most of the layers < 1.1.82 but the `VK_LAYER_EOS_Overlay (Vulkan overlay layer for Epic Online Services)` persists and does not show up in regedit. Is there any way to manually flush this?

**Comment by jfaz1** [comment]
Thanks for the detailed response. I managed to remove most of the entries but I can't seem to find any of the `VK_LAYER_EOS_Overlay (Vulkan overlay layer for Epic Online Services)` in regedit, I tried using the search tool to no avail. Any clue where it could be stored/how else I can reset it?

**Comment by frank-ourmachinery** [comment]
If the layer isn't in the registry under ImplicitLayers then it shouldn't be added automatically. Given that it's a service from Epic, maybe you could try to shutdown all Epic Games applications? I think we should probably downgrade our minimum required version to 1.1 instead of 1.1.82. If anything I think that might be what's causing this.

**Comment by jfaz1** [comment]
Yeah I've tried shutting down everything related to Epic Games, restarting, etc. but it doesn't seem to go away. This one's on me since I can't figure out where the hell it is, but if you guys end up downgrading the minimum version please let me know so I give it another shot.
