### ISSUE TITLE
Crash on startup when loading project where tm_buffers has been deleted

### ISSUE THREAD

**Issue by JoNil** [OurMachinery/themachinery-public#360]
Steps to reproduce:

1: Download and open the animation example
2: Save out the project into individual files
3: Open the expanded project
4: Close the-machinery
5: Remove all folders in the project named: *.tm_buffers

Now then opening the machinery it immediately crashes on startup with this dump: https://drive.google.com/file/d/1V1O31ylj2HSZ7EikwZTqn8ThOfQJxHny/view?usp=sharing

I'm running the-machinery: 2020.11

I tried applying the full dump registry vars but the size of the dump didn't change so i dont't think it worked for me.

**Comment by niklas-ourmachinery** [comment]
I don't think we can guarantee that The Machinery will always behave nicely if you mess around with its files.

But I think this case (missing files) should be handled better, because it is something that can happen quite easily (for example if someone forgets to add an asset to git).

We might not be able to continue to open the project if crucial files are missing, but we should at least display an error dialog box with a message rather than crashing. Will look into it.

**Comment by JoNil** [comment]
"I don't think we can guarantee that The Machinery will always behave nicely if you mess around with its files."
Totally understand that.

In my case it happened when i wrote my gitignore file for the repo, i didn't realize that the tm_buffers folder where necessary, so one git clean later ¯\_(ツ)_/¯

**Comment by niklas-ourmachinery** [comment]
Fixed for next major release (2020.12). If a problem is detected during project load you will now get this error message:

![image](https://user-images.githubusercontent.com/26548514/100019016-3e61bd00-2d92-11eb-8705-709250fc12f5.png)

I left an option to still open the project, because it might be the case that you only have this copy of the project, so you just want to keep your fingers crossed, try to open it and hope that you can salvage something from it.

@tobias-ourmachinery If I choose [Open Anyway] in the repro above it will crash on `vkCmdBindIndexBuffer(vk_buf, ibuf, 0, itype);` in `vulkan_render_backend.c:4972`. Perhaps we should make this code more stable so that it doesn't crash on missing buffers?

**Comment by tobias-ourmachinery** [comment]
@niklas-ourmachinery I agree, will look into it.

**Comment by frank-ourmachinery** [comment]
The crash seems to have been resolved by now. It's also more difficult to load into a corrupted project at all now, which I think is a good idea. This issue seems to be resolved by now so I'll close it. It's probably best to create a new "enhancement" issue if we want to support some kind of recovery.
