### ISSUE TITLE
Crash on high values in the creation graph

### ISSUE THREAD

**Issue by JoNil** [OurMachinery/themachinery-public#366]
This is something that doesn't affects me but i just wanted to let you know. There are some places in the creation graph where if i enter high values the editor will crash, some examples:

- On the box node if I enter 10_000 in the tessellation field
- On the plane node if I enter 10_000 in the tessellation field
- On the uv sphere node if I enter 100_000 in the meridian or parallels field
- On the draw call node if I enter 100_000 in the instance count field

All of these seem like gpu out of memory issues, one solution would be to clamp the values. But i have no idea if that is something that you want to do. Maybe there is even some way to handle this gracefully without imposing an arbitrary limit, but that seems hard.

Tell me if you want crash dumps from any of these!

**Comment by niklas-ourmachinery** [comment]
Yes, not 100 % sure what the right thing to do here is. We could put in limits everywhere to protect users from themselves, but that's a lot of limits to put in. Also, what if someone *really* wants to test run with high tesselation and they have a super beefy machine that can handle it... doesn't feel right to limit users to something below what their machine can handle.

And of course, finding out what the machine can handle could be tricky, especially since it depends on what else is going on at the same time.

Will have to think about this one.

**Comment by frank-ourmachinery** [comment]
The crash on the draw call node with ~100.000 instances is a driver specific issue. The device lost exception is likely caused by a GPU timing issue when rendering that many instances of a mesh. I tried batching them together into draw calls of 1000 instances to see it that would solve the crash, but it still does.
There is no real way for us to check whether the specified number instances are reasonable for the hardware executing the instructions, so leave this driver crash in. 

The tessellation related crashes do seem to be memory related, maybe we can put a reasonable limit there.
