### ISSUE TITLE
tm_plugins_api->unload() crashed on free()

### ISSUE THREAD

**Issue by kasicass** [OurMachinery/themachinery-public#371]
![1](https://user-images.githubusercontent.com/104400/100996758-69b78980-3594-11eb-8227-0937a4f5523f.png)

**Comment by niklas-ourmachinery** [comment]
This crash is in the Windows heap checker. A crash there is typially a sign that you are doing something wrong with memory, either overwriting memory bounds, freeing something twice, etc.

Since you have your own executable and DLL that bad memory operation might be in there (and not in our code).

To debug it, I suggest using the `tm_allocator_api->end_of_page` allocator instead of the standard one. This will typically give you an error where you do the bad operation (instead of later when Windows checks the heap).

If you used `simple_3d` as a template for your application, you have this code in there:

~~~c
const bool USE_END_OF_PAGE_ALLOCATOR = false;
    tm_allocator_i *standard_allocator = USE_END_OF_PAGE_ALLOCATOR ? tm_allocator_api->end_of_page : tm_allocator_api->system;
    tm_allocator_i a = tm_allocator_api->create_child(standard_allocator, "application");
~~~

Change it to `USE_END_OF_PAGE_ALLOCATOR = true`.

Note: You only want this while your diagnosing the problem, since the end of page allocator is a lot less efficient than the standard one.

**Comment by niklas-ourmachinery** [comment]
Closing this one for now since most likely it is an issue with your plugin and not The Machinery. Feel free to reopen if you need additional assistance.
