### ISSUE TITLE
"Import Assets" button doesn't show when multi selecting dcc_assets

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#377]
It would be very handy to be able to do a multi-rig of DCC assets

**Comment by karl-ourmachinery** [comment]
We need  to fix a few things to do this in a nice way:
- Make the DCC asset property UI make use of the multi-edit properly
- Make the finding of Import Settings more efficient. Currently it scans though the whole asset list of the project. It should build some smart directory lookup for Import Settings, so it can quickly figure out where the closest import settings asset is for each file in the multi select.
- Build an umbrella-task that keeps track of all the separate import tasks

**Comment by niklas-ourmachinery** [comment]
#460 has been fixed... multi-edit is now shown.

I also improved the finding of Import Settings earlier.

I think the [Reimport From...] button doesn't make sense for multiple assets, because you don't want to pop multiple windows... so it's probably only the [Reimport] button that we need.

Do we really need an umbrella task? Can't we just post *n* tasks for it?

I'll take a stab at implementing this and notifying you @karl-ourmachinery  when it's done.

**Comment by niklas-ourmachinery** [comment]
Fixed for 2021.4.
