### ISSUE TITLE
Material double-sided setting is ignored

### ISSUE THREAD

**Issue by infosia** [OurMachinery/themachinery-public#417]
Material "Double Sided" setting is ignored when you extract dcc assets. 

Tested by [this model](https://github.com/infosia/themachinery-issues/blob/master/0008/Vita.fbx).

**Comment by frank-ourmachinery** [comment]
This seems to be a problem with [Assimp](https://github.com/assimp/assimp) itself. The culling shading property is not supported by their FBX converter so when we query whether it's double sided it will always return false. 

Currently FBX models will need some manual material parsing in order to be correct. Until this is fixed in Assimp I would suggest making a copy of the default material graph and manually setting the Face Culling mode to Double Sided in the Surface Settings and then using that material to import the model.

**Comment by tobias-ourmachinery** [comment]
I've added all fallbacks I can think of for detecting if an assimp material needs transparency or not, but from what I can tell both materials in this mesh will report as opaque. 

The good part is that its now way more simple to adjust the incorrect material after the import. Just change the material's prototype to `dcc-material-opacity` and things will be rendering correctly in 2020.5. 

![image](https://user-images.githubusercontent.com/26548681/119836448-0a628280-bf02-11eb-918f-6425268b6410.png)
