### ISSUE TITLE
unicode issues when compiling my plugin

### ISSUE THREAD

**Issue by Qskotlv** [OurMachinery/themachinery-public#421]
Some files should be encoded as utf8-BOM, otherwise it will trigger Unicode errors.
When I build a plugin in vs2019, it failed.

the outputs :
![image](https://user-images.githubusercontent.com/54298229/102475784-48c35e00-4095-11eb-99d8-db14f86862db.png)

The file contains characters that cannot be represented in the current code page (936). Please save the file in Unicode format to prevent data loss.

After I encoded is as utf8-BOM, it fixed.

files :  foundation\unicode_symbols.h

**Comment by niklas-ourmachinery** [comment]
This Works For Me™ -- maybe because I have different language system settings.

I'm not 100 % adding the UTF8-BOM is the right fix:

* Visual Studio recognizes the UTF-8 BOM: https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-160
* But Unicode does not recommend adding an UTF-8 BOM: https://stackoverflow.com/questions/2223882/whats-the-difference-between-utf-8-and-utf-8-without-bom

Personally I think BOMs are a bit ugly. Maybe we should use the `/utf-8` flag instead.

Does using `/utf-8` work for you?

**Comment by niklas-ourmachinery** [comment]
I've added `/utf-8` to the build flags.
