### ISSUE TITLE
Workflow when you have assets inside the project folder

### ISSUE THREAD

**Issue by Srekel** [OurMachinery/themachinery-public#435]
I'm not sure if this is a bug or a feature request or both but...

I feel like if I have an asset already in the project's folder, it should be added/imported automatically (unless perhaps I have previously explicitly excluded it).

If this is intentional, then I would assume that simply dragging an asset from within your project folder into TM window would import them into the "same" path. It feels weird that they are in different places in the folder hierarchy and inside TM's asset browser. 

I could potentially see a use for having assets in different places but that seems like something you'd want to do explicitly for special cases.

**Comment by Srekel** [comment]
I now had a folder added twice. I tried removing one of them (the one whose path did not match the physical path) and TM crashed.

**Comment by niklas-ourmachinery** [comment]
I think it is a feature request 😄 .

Currently, we don't really support modifying the project folder on disk *while the engine is running*, and doing so can lead to problematic things. You are expected to do all the changes in the asset browser.

The Machinery holds an in-memory copy of the project state, which may be different than the disk state, so if you change stuff on disk you may end up in tricky situations. For example, a file might be modified both in-memory and on-disk leading to conflicts about what is "the right version".

But I think you are right that we should support some \disk modifications, since the users might expect that to work. The best thing would probably to have a directory watcher that watches for changes on disk and if we detect any we pop a window that says:

> Changes to the project on disk where detected: [Import] [Ignore]

That same window can then also show a warning if an asset has been changed both on disk and in memory.

**Comment by niklas-ourmachinery** [comment]
Further fleshing this out:

* If The Machinery files are detected, we should just add those assets to the project.
* If non-The Machinery files are detected, we should run import on them.

Supporting this fully is not a completely trivial thing to do. We would have to find whatever has modified on disk, whatever has modified in-memory and then do a merge between the changes.

**Comment by niklas-ourmachinery** [comment]
I added a fix for this. If you change any The Machinery files on disk (such as with `git pull`) you will be prompted with a modal dialog where you can choose to:

* Import the disk changes
* Discard the disk changes

If you have any unsaved in-memory project changes, choosing "Import" disk changes will discard the in-memory changes. I.e., we do not try to "merge" in-memory and "disk" changes. Instead, in that case the recommended approach to merge is to discard the disk changes... revert the disk files to before you did `git pull`, save your in-memory changes and then use `git` to merge the changes on disk.

(In theory, we could try to merge in-memory and disk changes, but it would become pretty hairy.)

When we check for disk changes we will *ignore* any file that is not a The Machinery file. I.e. you cannot import stuff by dragging it into the project folder. Jpegs, models, etc dragged into the project folder will just be ignored. (You can of course import them by dragging them into The Machinery window instead.)

We felt like this was the best approach... allowing importing by dragging to the project folder "blurs the lines" between what is project data is not, and also encourages the user to manipulate files directly on disk. Since we can't merge in-memory changes with disk changes we don't want to encourage users to make changes directly on disk, but to make them in the editor as much as possible.
