### ISSUE TITLE
Editor camera speed resets frequently

### ISSUE THREAD

**Issue by Srekel** [OurMachinery/themachinery-public#442]
I find I often have to scroll in order to increase the camera speed, and it can reset at various times. I think this time it reset just by going into the Editor Settings window and changing the camera far plane.

This, plus that scrolling to make it faster/slower is very insensitive - I have to scroll a lot to get to the speed I want - makes it a bit painful.

**Comment by frank-ourmachinery** [comment]
There was a bug where you could zoom a camera that was not active, this often reset the camera's speed properties. After fixing this I've tried to recreate a scenario where the camera speed resets and I wasn't able to, (unless I close the entire scene tab).

The speed will get less sensitive as you increase it as the speed increase on an exponential curve. I think it might be a good idea to expose some constants to a settings tab in order to allow you can alter the sensitivity. I created a new issue for this: #550
