### ISSUE TITLE
Dragging a dcc asset into the scene isn't undoable.

### ISSUE THREAD

**Issue by Srekel** [OurMachinery/themachinery-public#454]
I'm dragging a model into the scene, hitting ctrl-z, it doesn't remove the new entity.

**Comment by simon-ourmachinery** [comment]
You can revert this when you select the Asset browser and press ctrl + z. This is a consequence how we currently implement.

**Comment by Srekel** [comment]
That doesn't work for me. And either way, it feels unintuitive. If I Ctrl-Z directly after an action, it should undo that action. Or if I have the scene/entity tree focused, it should also undo additions.

**Comment by niklas-ourmachinery** [comment]
Yeah we need to think about this a little...

Undo events are tied to specific assets. This is so you can have different undo stacks for different tabs. (This is how Undo works in Visual Studio for example... you can work in one tab without destroying the undo stack of a different tab -- which you would if all tabs shared a single undo stack.)

The reason we tie events to *assets* rather than to *tabs* is that if they were tied to *tabs*, you would lose the possibility to undo if you closed the tab. (This is also how Visual Studio works... if you have multiple tabs showing the same file, they share the same undo stack.)

This works pretty well... when it becomes tricky is when you have events that touch more than one asset... where should the undo events go?

Currently... such events go into the "Asset Root" undo stack... and they can only be undone from the asset browser. This is sort of understandable when the events come from the asset browser (copying and deleting assets).

But it becomes pretty weird when events touch multiple assets for other reasons... say for example you drag an entity form one scene asset to another... now you touched two assets... so you have to undo it from the Asset Browser... weird...

A better solution might be -- if something touches multiple assets it goes into "all" the undo stacks of all the things it touched. (I think this is kind of what Visual Studio does if you do Find & Replace across multiple files.) This might work better, but I need to think about it a bit more to see if there are any other problems with it.

**Comment by niklas-ourmachinery** [comment]
@Srekel FYI -- Undoing it in the Asset Browser works for me:

![454](https://user-images.githubusercontent.com/26548514/105913098-3831cc00-5fe1-11eb-99a5-34dcc018d52f.gif)

**Comment by Srekel** [comment]
Ok, looking at it closer there are two cases.

First, dragging an **entity **from the asset browser into the scene.

The first undo command is `Undo: Select Dropped Entity`. Only after that's done can you undo (remove) the added entity. Those two should be grouped into one command. Currently when you undo once it doesn't undo the "actual" action you did, which is confusing.


Then, dragging a *dcc_asset** into the scene.
The first undo command is still `Undo: Select Dropped Entity`. But after I do that, there is no way to undo the adding of the entity from the scene tab. This is probably what I found confusing initially.

I can select the asset browser and undo, this removes the entity asset, and also the entity from the scene (which is reasonable). 

I would like to be able to undo adding the entity from the scene but still keeping the entity asset. Or, I would be fine with undoing the entity from the scene also removing the entity asset, if it was created just for that. I'm not sure what the correct workflow is here, I think personally I would like the entity asset to be kept.

**Comment by leonardo-ourmachinery** [comment]
I elaborated a bit on this issue, and I think something that may work reasonably OK is:

-when an asset is dragged _into_ the scene tab, we'll record entity creation + selection on the scene undo stack. This means that if you Undo right away the entity will be unselected and deleted immediately.
-depending on what you drag, the asset browser may end up doing "collateral" stuff, like creating/extracting assets. These changes should be pushed into the Asset browser undo stack, as it's stuff that the user didn't "directly" do.
-This of course means that to Undo the "collateral" stuff that the asset browser did, you have to click there and undo. But I think it makes sense as its stuff that the user didn't actually "did"... what the user cares about the most is the entity in the scene.

I think that in the vast majority of use cases there's no need to push the changes to multiple stacks, but it's better to think about what should go in which undo scope and potentially make some tradeoffs, like in this case.

@Srekel @niklas-ourmachinery I can try to work on this for the 2021.12 version if you both like what I've proposed.

**Comment by simon-ourmachinery** [comment]
I ran into a similar issue today in which I imported an asset and deleted it. Renamed/moved another asset in the asset browser. The result was that I could not undo the rename/move. This was due to the fact that these actions are added to the undo stack of the property view/root object. 

I think this is a general problem we have with our document undo concept that it just sometimes can lead to confusing behavior.
