### ISSUE TITLE
Wrong texture shown for fbx assets

### ISSUE THREAD

**Issue by infosia** [OurMachinery/themachinery-public#479]
I noticed wrong texture shown for some fbx assets from mixamo especially around faces.

Expected:
![expected](https://raw.githubusercontent.com/infosia/themachinery-issues/master/0011/expected.png)

Actual:
![actual](https://raw.githubusercontent.com/infosia/themachinery-issues/master/0011/actual.png)

https://github.com/infosia/themachinery-issues/blob/master/0011/kaya.fbx

**Comment by tobias-ourmachinery** [comment]
This is not a texture related problem. It happens because our automatically rigged material graphs ignores alpha masking and opacity. Everything is fine if we hook up the alpha of the base color to the opacity input for the mouth and eye brows materials. 

We should probably try to come up with a way to take opacity into account when rigging the default material graphs.

![image](https://user-images.githubusercontent.com/26548681/119793959-58ae5c00-bed7-11eb-926a-64288d107dcb.png)

**Comment by tobias-ourmachinery** [comment]
This was fixed for 2021.5 but I forgot to close it. Closing now.
