### ISSUE TITLE
Misleading error message when loading plugins

### ISSUE THREAD

**Issue by marot** [OurMachinery/themachinery-public#483]
I created a plugin asset and tried to load the `tm_minimal.dll` created by the `Minimal` example plugin.

When creating a plugin asset manually without changing the file name

![image](https://user-images.githubusercontent.com/74212402/108065412-41510e80-705e-11eb-9ffa-64cf3562212b.png)

the following error is logged:
`Plugin: The Plugin plugin does not support Windows Currently`.

Only when dragging in a dll I discovered that the `File Name` needs to match the dll file name.

**Comment by karl-ourmachinery** [comment]
It's actually that the DLL filename needs to start with `tm_`, which will be the case when dragging the compiled DLL in. We should make this clearer.

**Comment by niklas-ourmachinery** [comment]
The log message here `Plugin: The Plugin plugin does not support Windows Currently.` actually appears before you have added the Windows DLL. At this point, since there is no Windows DLL the plugin can't (obviously) be loaded on Windows.

However, I think this message is actually more confusing than helpful and I'll just remove it.

@karl-ourmachinery is right that the reason the DLL is not loading is that it doesn't start with `tm_`.

There are situations where having DLLs that do not begin with `tm_` makes sense... if your `tm_` plugin depends on an external DLL, you can add that as a plugin asset without the `tm_` prefix and your plugin should be able to load it. However, I think we should insert a warning in the Properties UI about the plugin not starting with `tm_`.

**Comment by niklas-ourmachinery** [comment]
Fixed for 2021.2.a:

![image](https://user-images.githubusercontent.com/26548514/109572573-57b98a00-7aa2-11eb-86c3-c514391aa28d.png)

**Comment by niklas-ourmachinery** [comment]
Sorry, @marot, you are right and I was confused. The requirement was actually for the asset name to start with `tm_`, not the import path.

I've fixed that in the hotfix for 2021.2.a, so that you can now use any name.

"External" DLLs weren't fully supported in this version, so I won't add support for them in this hotfix... I will do that in a future full release instead. And I will identify them by a checkbox in the UI rather than by naming convention.
