### ISSUE TITLE
Adding an Asset label to an asset will make project dirty but the assets won't be shown in the "modified assets" tab

### ISSUE THREAD

**Issue by leonardo-ourmachinery** [OurMachinery/themachinery-public#485]
.

**Comment by simon-ourmachinery** [comment]
The suspected reason is that the `tm_asset_save_status->status` function takes only the version of the sub object and compare them. The version of the asset changes when a label gets added. Adding the check of the asset version will lead to a double display of changes in the "modified assets" tab. This is because changes in assets are checked separate, to provide some auto information about the change: such as rename, move, deleted... The general changes (requested via the status function of the same interface) are appended to the list.

The  documentation of the status function is quite miss leading:
```
   // Return the saved status of the specified asset.
    enum tm_asset_save_status (*status)(tm_asset_save_o *inst, tm_tt_id_t asset);
```
In fact this function return the status based of the sub object. This is also why the asset browser will not pick up if a file has been renamed.

Therefore a change in logic is required. I am unsure what we want. Maybe @niklas-ourmachinery  has a better idea.
