### ISSUE TITLE
Profiler Freezes when opening save dialog

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#487]
When trying to save the record the engine freezes in opening the save modal.

**Comment by niklas-ourmachinery** [comment]
Could not reproduce in 2021.2. Can you provide more detailed steps maybe?

**Comment by niklas-ourmachinery** [comment]
Managed to reproduce it. The call stack is frozen in the `EnableWindow()` Windows API call, called from `private__enable_windows()` in `os.win32.c`.

**Comment by niklas-ourmachinery** [comment]
I think this is caused by the multithreading of the UI. The profiler UI update might run on a separate window than the window was created on.

https://microsoft.public.win32.programmer.kernel.narkive.com/0PRy9Umk/is-enablewindow-hwnd-bool-thread-safe :

> Yes, you can call EnableWindow(HWND, BOOL) from a thread that did not
create the window. BTW, that is exactly what CWnd::EnableWindow does.
> 
> This will often work as intended. But, for both the API and MFC cases,
the call blocks until the thread that created the window processes
messages. If the thread that created the window is suspended then your
program deadlocks.

**Comment by niklas-ourmachinery** [comment]
Investigating this a bit more... even regardless of the `EnableWindow()` issue, it seems like just calling `GetSaveFileName()` from another thread than the main UI thread will result in the application freezing.

I think to fix it, we must run it as a job that we pin to the main UI thread. (The other option would be to disable the multithreading of any UI that can open a dialog box, but that means that we lose most of the multithreading in the UI.)

**Comment by niklas-ourmachinery** [comment]
Fixed.
