### ISSUE TITLE
Cannot input Russian text

### ISSUE THREAD

**Issue by endragor** [OurMachinery/themachinery-public#516]
The Machinery 2021.2.a
Windows 10 Pro Version 1909

When trying to input text in Russian keyboard layout into a text field, it looks as if an incorrect 8-bit encoding is used instead of UTF-8. For example, instead of `Привет` you get `Ïðèâåò`.

Also, if you try to copy and paste `Привет`, you get spaces instead of the string.

**Comment by frank-ourmachinery** [comment]
Currently we use the Segoe+UI+Symbol font on Windows, which sadly doesn't support Cyrillic, so it will display spaces for glyphs that aren't loaded. I'm not entirely sure why the character encoding is wrong if you just type instead of paste, I'm assuming that is because we currently only support English and Swedish. 

I hope we can add support for this in the future, but it probably means getting a custom font to support various common scripts like Cyrillic.

**Comment by niklas-ourmachinery** [comment]
@frank-ourmachinery Are you sure the font doesn't support cyrillic? I think it's more likely that we're just not loading the cyrillic glyphs.

I'm confused about what happens with the typing... typing should yield the same result as pasting... not sure what goes wrong with that. There might be issues with how we handle multibyte characters while typing.

**Comment by frank-ourmachinery** [comment]
@niklas-ourmachinery I checked the font we use with Windows Character Map and I also added Cyrillic to the Unicode ranges when loading the UI font. When I paste the example you get white squares instead of spaces, which in my opinion is more preferable.

**Comment by infosia** [comment]
I saw similar issue with Japanese IME #406 Saw spaces when I paste Japanese character.

**Comment by frank-ourmachinery** [comment]
It turns out that the Win32 windows were not fully Unicode compatible, so the inputs were translated into ASCII instead of UTF-16. In the next release you should now be able to input Cyrillic (and hopefully other) non-ASCII glyphs. The default font on Windows (Segoe) still doesn't support Cyrillic though, so you'll see white boxes for now.

Segoe:
![image](https://user-images.githubusercontent.com/70658773/112620412-caf7b700-8e28-11eb-8ef3-eb8f46666065.png)
Arial:
![image](https://user-images.githubusercontent.com/70658773/112620496-e6fb5880-8e28-11eb-9a27-3ca516ca0bc2.png)

I tried to also add the CJK range, but that ended up costing me 7GB+ worth of ram, even for just the unified ideographs. So I think we need to come up with a way to solve those separately.
