### ISSUE TITLE
tm_ui_textedit_picker_t::search_text_len - in bytes or in glyphs?

### ISSUE THREAD

**Issue by endragor** [OurMachinery/themachinery-public#518]
It's unclear from the documentation whether the length should be specified in bytes or in glyphs. tm_ui_api::textedit uses glyphs, that's why the question arises. Also, when reading docs for such APIs, I always wonder "should it also include a NULL character or not?". If it's unclear, I prefer to specify one byte less just in case...

**Comment by frank-ourmachinery** [comment]
The `tm_ui_textedit_picker_t::search_text_len` field is specified in glyphs, the null terminator should be included in this. The documentation will be updated for the next release.

**Comment by niklas-ourmachinery** [comment]
That's incorrect. The length is specified in bytes. (Which is proof that the documentation really needs to state this.)

When you pass a string for an API function to fill, as in this case, the length should aways be the size of the buffer. I.e., bytes and including the NULL character, so that you are able to do this:

~~~c
char my_buffer[128];
do_something(my_buffer, 128).;
~~~

If we *return* the length of a string... we return the length in bytes, not including the `\0` -- i.e., same behavior as `strlen()`.

The only place we ever use glyph indices or glyph length is after we have converted from UTF-8 to a list of code points.

Side note: I think using glyph indices when dealing with UTF-8 strings is just confusing... if you want to refer to a specific glyph in an UTF-8 string, use a `const char *` pointing to that glyph instead of a glyph index.

I'll fix the documentation so that it says the right thing :)

**Comment by endragor** [comment]
> When you pass a string for an API function to fill, as in this case, the length should aways be the size of the buffer. I.e., bytes and including the NULL character, so that you are able to do this

The [textedit()](https://ourmachinery.com//apidoc/plugins/ui/ui.h.html#structtm_ui_api.textedit()) I mentioned doesn't follow this convention, that's why I was initially not sure what to pass to `tm_ui_textedit_picker_t::search_text_len`. [textedit()](https://ourmachinery.com//apidoc/plugins/ui/ui.h.html#structtm_ui_api.textedit()) requires you to specify the size in glyphs. So `ui_sample_tab.c` has buffers of size `32 * 4` and then passes `32`, and `survey.c` passes `edit_buffer_size / 4`. At the same time, when the text is not being edited, `survey.c` passes the value of `strlen(text)`, which is in bytes and doesn't include the NULL terminator. So the whole thing is pretty confusing, as C string APIs tend to be...

**Comment by niklas-ourmachinery** [comment]
Yes... agreed...

I thought it would make sense for `textedit()` to take a maximum length in glyphs, because you typically want to say *"give me a textedit box with room for 30 characters"* and not *"give me a textedit box with room for 30--120 characters depending on what kind of characters the user types"*.

I.e. we want the UI to stop accepting input after *n* characters where *n* is a fixed number, rather than after however many characters will fit in the UTF-8 encoded buffer.

But maybe it would be better to take the size of the buffer and then just limit the number of input glyphs to `(size - 1)/4`. Or maybe that's confusing too...

**Comment by niklas-ourmachinery** [comment]
And I see now I was wrong and @frank-ourmachinery  was right... it is passing the argument to `textedit()` so it is in glyphs and not in bytes... yes... it's all really confusing.

We should probably change them all to just use bytes...

**Comment by niklas-ourmachinery** [comment]
I'll reopen this to consider if we should change the API and pass everything in bytes...

**Comment by endragor** [comment]
> I thought it would make sense for textedit() to take a maximum length in glyphs, because you typically want to say "give me a textedit box with room for 30 characters" and not "give me a textedit box with room for 30--120 characters depending on what kind of characters the user types".

That makes sense. I just think the documentation has to be explicit about this where needed and also about how it uses the value when the string is not being edited. E.g. I guess `survey.c` using `strlen` works because it ignores the value when the string is not being edited? Or maybe it does use the value, but it works only as long you use ASCII characters... Still not sure about that.

On the other hand, it's hard to set a meaningful character limit. Why would I want to limit a text box to 30 characters? Usually, it has to be "large enough" for whatever the user types. And if I need a limit, I could enforce it by validating the input.

By the way, "glyph" can also be a confusing term. It usually means a shape from a font rather than a character. Ligature fonts have glyphs that represent multiple characters. So "character" is a better term, but it can probably be confused with C's `char` type which is actually a byte. "code point" is another term, but a code point is a number, that doesn't define how it's actually represented in memory, which is important here. Anyway, if you are going to change limits to bytes, you won't have to deal with this :)

**Comment by niklas-ourmachinery** [comment]
Yes, I think using bytes is just less confusing all around :)

**Comment by niklas-ourmachinery** [comment]
Fixed for 2021.4.

Together with fixing this, I also fixed a *ton* of places where `textedit()` was used incorrectly.

I think the old API was confusing enough to consider this an [API Bug](https://ourmachinery.com/post/dig-shallow-graves/).
