### ISSUE TITLE
Crash when switching projects

### ISSUE THREAD

**Issue by frank-ourmachinery** [OurMachinery/themachinery-public#524]
Steps to reproduce:
- Load into a sample project.
- Go to the download tab and switch into another one.
- The Machinery crashes.

It's because the asset browser is trying to use the icon font whilst it is not available.
```
E:\Git\themachinery\plugins\ui\ui.c(2095): error: No default font set
E:\Git\themachinery\plugins\ui\ui.c(2095): error: No default font set
Exception thrown: read access violation.
icon_font.**font** was nullptr.
```

**Comment by niklas-ourmachinery** [comment]
Fixed for 2021.3.a.

This was pretty gnarly so here's a short summary:

* The bug happened when exiting a modal dialog popped by the Download tab.
* Root cause is that the inner (modal) tick loop calls `tm_ui_api->clear()` before it exits which clears the font data that is stored at the start of the UIs `vbuffer`.
* If anything tries to draw text at this point (before we loop back to the beginning of the outer ticker loop where we repopulate the font data) we will crash.
* I fixed it by not calling `tm_ui_api->clear()` when we exit the inner (modal) tick loop.
* This has the added benefit that we no longer need to save the drawn UI in *modal_saved*. Since we no longer clear the UI, it will contain all the drawn data.
