### ISSUE TITLE
I would like to see property values for unoverridden entities/components

### ISSUE THREAD

**Issue by Srekel** [OurMachinery/themachinery-public#528]
I feel like I often want to be able to inspect an entity I've dragged in. For example to check how something I've added from core is set up. Currently I need to override whatever it is I'm looking at, then undo it.
![image](https://user-images.githubusercontent.com/1578924/113410530-ef690b80-93b3-11eb-8d20-ebd01af2e783.png)

**Comment by simon-ourmachinery** [comment]
Sorry wrong button.

I think this requires the changes we discussed once about the not changeable properties ? Aka read only text views etc. What do you think @karl-ourmachinery ?

**Comment by Srekel** [comment]
A suggestion would be to not make them unchangable. Rather, if I haven't overridden anything, just show it as is. 

When I, for example, set a bool from false to true, that marks the entity/component as overridden automatically.

Preferably, the bool should be explicitly shown as being different from the original. 

Reverting back to the original should remain an explicit step.

**Comment by niklas-ourmachinery** [comment]
To implement this we would have to do something similar in the property view to what we already do in the tree view -- keep track of when we are viewing an "inherited" child as opposed to an instance one.

It could either be shown in read-only mode... or it could be shown as editable (just as an instanced child) and when you start editing it, we would instantiate the whole chain of "inherited" nodes from the first non-inherited object down to the current edited item.

This should all be doable... the main issue is that it would increase the burden of anyone writing a custom property editor (which we do a lot!) since those custom property editors would have to be aware of this extra editing mode.

Maybe we could do something like creating a pseudo-instance of the object for editing... but not *actually* instance the object until anything is changed. That way, the property editors wouldn't have to do anything special for this case as long as they work with instances today, they would automatically work with this setup.

**Comment by simon-ourmachinery** [comment]
related to #447

**Comment by leonardo-ourmachinery** [comment]
Another problem that we have atm is that components that are not instantiated cannot be selected in the Entity Tree, and so that means that if an Entity has a Camera component (not instantiated) you cannot click on the camera component to activate the "Camera preview" in the preview tab.

**Comment by karl-zylinski-ourmachinery** [comment]
This has been mostly fixed for 2021.11. You still can't select inherited components etc, but that's what #447 is about.
