### ISSUE TITLE
Crash after resizing window

### ISSUE THREAD

**Issue by Srekel** [OurMachinery/themachinery-public#535]
I'm not sure what caused this to happen or what state I was in at the time, but the last thing I did was resize the window, and a second or so after that, TM exited.

Uploading a few .dmps, I believe one of them should be that crash.

[dumps.zip](https://github.com/OurMachinery/themachinery-public/files/6252783/dumps.zip)

**Comment by frank-ourmachinery** [comment]
The crashes associated with dump files 1, 3, and 4 are related to the cubemap capture component. We're aware that the component is unstable at the moment, this will be fixed for the hot fix release, hopefully soon.

The second dump file fails because on an indexed draw call missing an index buffer. It's quite silly that we don't check for this and throw a better error. Not sure where this draw call came from.

I can't find any reason why resizing the window would cause these crashes, I'm pretty sure it's the cubemap capture component. I would suggest removing it from your scenes until the hot fix release.

**Comment by niklas-ourmachinery** [comment]
The cubemap crash is fixed for 2021.3.a. If any crashes remain after this, please report them as separate issues.
