### ISSUE TITLE
Moving camera in the scene hides transform gizmo

### ISSUE THREAD

**Issue by endragor** [OurMachinery/themachinery-public#539]
The Machinery 2021.3
Windows 10 Pro Version 1909

When moving the camera in a scene by holding the right mouse button, transform gizmo gets hidden. I don't think there is a reason to hide it. Often you actually want to reposition the camera to get a better idea of where the gizmo origin is at and hiding it makes that difficult. Also, the gizmo doesn't get hidden when you zoom with the mouse wheel, which is also a form of camera movement.

**Comment by frank-ourmachinery** [comment]
This was due to another issue (#491) where you could select the gizmo when the scene view camera was in free flight mode. I just disabled the gizmo from being active whilst the camera was in free flight as we had no way of only rendering the gizmo without it being able to be selected. 

I added a render only mode to the gizmos now for next release and fixed this bug.
