### ISSUE TITLE
Startup crash in beta-2021.3-windows

### ISSUE THREAD

**Issue by drrosa** [OurMachinery/themachinery-public#542]
After downloading beta-2021.3-windows, I was able to run `the-machinery.exe`, `simple-draw.exe`, and `simple-3d.exe` without issues, but only once. Then after I restarted my PC, none of the .exe files work anymore... I tried deleting the folder, and unzipping `beta-2021.3-windows.zip` again and even switched Windows user accounts, but that didn't work either.

Now, whenever I run `the-machinery.exe`, a `.dmp` file is generated:
[the_machinery_exe 2021-04-05 21.37.59.zip](https://github.com/OurMachinery/themachinery-public/files/6259130/the_machinery_exe.2021-04-05.21.37.59.zip)
 and here's the log file too:
[2021-04-05 21.37.59.log](https://github.com/OurMachinery/themachinery-public/files/6259079/2021-04-05.21.37.59.log)
and the full crash dump:
[the-machinery.exe.12468.dmp](https://we.tl/t-VSQI42EGNl)

But other than that, nothing else happens after I run any of the .exe files.

I also downloaded the `beta-2021.2-windows`, and oddly enough, all three programs work just fine in this previous version.

**Comment by niklas-ourmachinery** [comment]
The crash happens in `vkCreateDevice()`, so it has something to do with the setup of the Vulkan device.

Here's three things for you to try:

1. Download the latest GPU drivers.
2. Start `the-machinery.exe` with the flag `--safe-mode` (or hold down F8 during launch). This disables loading of the setting files. There might be a bad value saved there that causes the crash (since you were able to run the first time).
3. You can also try outright deleting the settings folder  `AppData\Local\The Machinery`.

**Comment by simon-ourmachinery** [comment]
@drrosa is this bug still there with the HitFix?

**Comment by drrosa** [comment]
@niklas-ourmachinery Thanks for the help!
@simon-ourmachinery 

Neither `-safe-mode` nor deleting the settings folder  `AppData\Local\The Machinery` worked.

But downloading the latest NVIDIA drivers and performing a clean install did the trick!

**Comment by simon-ourmachinery** [comment]
@drrosa thank you for your info!
