### ISSUE TITLE
Editor panel doesn't reflect runtime state 

### ISSUE THREAD

**Issue by julhe** [OurMachinery/themachinery-public#634]
When I wrote a component that would change the transform, this confused me a bit! It would be nice for debuging purpose if I could see the actual runtime state.

**Comment by niklas-ourmachinery** [comment]
I don't think we want this to happen automatically (as it does in Unity I think), for several reasons:

* It can be confusing to know whether you are viewing the runtime state or the editor state.
* Runtime state and editor state may not match (i.e. there is not always a clear 1-1 correspondence between what exists in the runtime and in the editor).

That said, I do think it would be useful to be able to view (and edit) the runtime state for debugging purposes, but I think we need a separate mechanism for this. First, a concept of "selected" entities in the runtime and then a way of viewing and editing their state (probably through the save-game system, since that is a generic system for reasoning about the runtime state of entities).

**Comment by simon-ourmachinery** [comment]
#49 related

**Comment by leonardo-ourmachinery** [comment]
The Simulation State tab (will be delivered in 2021.11) will allow you to see/edit/writeback to scene the runtime state of the entities.
