### ISSUE TITLE
[UX] Camera view from a different scene viewport

### ISSUE THREAD

**Issue by jamesmintram** [OurMachinery/themachinery-public#641]
I tried this yesterday and couldn't figure out how to do this:

View my open scene in 2 viewports/tabs
1 viewport will be set to view through a camera
2nd viewport will be the "Normal" editor view

I struggled to find a way to open multiple scene viewports.

Not sure if this is a bug, or just unimplemented functionality,

**Comment by jamesmintram** [comment]
So I have investigated this some more and came to the "tab selection" policy:
```
static inline bool private__better_score(struct score_t a, struct score_t b)
{
    if (a.asset_match != b.asset_match)
        return a.asset_match;
    return a.age < b.age;
}
```

I tweaked it to ignore the fact that an asset is already being shown in a tab, and used only the most recently selected tab.

```
static inline bool private__better_score(struct score_t a, struct score_t b)
{
    return a.age < b.age;
}
```

This made it very easy to achieve what I wanted:

![image](https://user-images.githubusercontent.com/108040/126234583-65a7358c-d6da-471f-957e-237eb1223e41.png)

Left tab is the normal "edit view" and right tab is the view through the camera.

I can see the argument for focusing a tab if the entity/scene is already open, but it makes it impossible to achieve the above - so I'd propose this as a possible behaviour for the editor?

Alternatively, the existing behaviour could remain and instead support dragging and dropping a scene onto a scene tab. That could provide the best of both worlds.

WDYT?

**Comment by geekrelief** [comment]
@jamesmintram I think you should make a PR out of this.  I'd like to see it as the default behavior.  Being able to see a scene from multiple cameras is more useful than focusing an already open entity.  I think the use case where you have so many tabs that you lose track of which entities are opened would be very rare.

**Comment by geekrelief** [comment]
@jamesmintram I think I understand the intent behind the Scene tabs better now after running into an issue #654.  The problem is that there's a difference in behavior with assigned Scene vs empty Scene tabs.  If you want to create multiple views you create an empty Scene, then use the dropdown menu to select the entity you want, then you have to click the light button.  The lighting should probably be on by default. 

https://user-images.githubusercontent.com/27040/126816639-d771f95a-4d84-4e52-9126-54f9cac93b3d.mp4

But it looks different from the Scene tab that has been assigned the entity.

https://user-images.githubusercontent.com/27040/126816844-5e7dae2e-a4c8-454b-b2f6-cd50fcbb84f5.mp4

**Comment by jamesmintram** [comment]
> But it looks different from the Scene tab that has been assigned the entity.
I did discover that and thought it was a bug due to the difference in behaviour between the two tabs, and after a couple of times doing it TM crashed on me.

**Comment by niklas-ourmachinery** [comment]
Changing `private__better_score()` is probably not a good idea, because there are other situations where that score is used to look for a tab with a specific asset.

A better approach to achieving this is to remove the `.find_asset` field in `tm_docking_find_tab_opt_t` in `open_entity_asset()` (`the_machinery.c:2453`) so the asset will be ignored in the search.

I tried this out and I think it works better. I think "the asset opens in the last focused tab" is a simpler behavior than "the asset opens in the last focused tab, unless the asset is already open in another tab in which case that tab gets focus".

Will merge this for 2021.7.

**Comment by niklas-ourmachinery** [comment]
Agree too that drag-and-drop should work for scene tabs, just as it does for simulate tabs.

**Comment by niklas-ourmachinery** [comment]
Will look into the different behavior issue... if it is a simple thing, I will fix it... otherwise I will create a new issue for it.

**Comment by niklas-ourmachinery** [comment]
Duh... dragging into the scene tab doesn't work, because that is already used for spawning the entity into the scene...

Unless we drag just to the tab itself (not the content of the tab)... but I think that's a bit too subtle to work nicely.

**Comment by niklas-ourmachinery** [comment]
Ok, investigated the behavior issue.

So what happens here is a little bit confusing, but I'll try to explain.

The dropdown menu that you are using doesn't actually select what scene to edit in the Scene Tab -- it selects which **lighting environment** to use.

Lighting environments are just entities like any others and they can contain geometry, etc. (For example, you may have a lighting environment that has geometry for a mountain backdrop.) In fact, any entity can work as a "lighting environment".

So when you select `world` in the list, you are not actually opening the world entity, you are setting the world entity as the lighting environment for the scene. Clicking the lightbulb enables and disables this lighting environment, which is why you see the scene pop in and out of existence.

This is admittedly confusing, and I actually had a talk with @karl-zylinski-ourmachinery about this a couple of weeks or so... I think it would be better if this dropdown only showed entities that were explicitly tagged as lighting environments.

I was unable to get the crash you mentioned though... if you can reproduce that please report it as a separate issue.

**Comment by niklas-ourmachinery** [comment]
Closing this as fixed with the change to the "open" behavior.
