### ISSUE TITLE
View camera frustum

### ISSUE THREAD

**Issue by jamesmintram** [OurMachinery/themachinery-public#643]
When I selected a camera, there was nothing indicating its frustum.

I eventually found a "show camera tags" button but the frustum rendering looked a little strange. Also, there was a circle rendered in the center of the viewport with this "camera tags" option enabled.

Is "show camera tags" the correct way to show the camera/frustum? 
Should a camera's frustum be rendered by default?

**Comment by frank-ourmachinery** [comment]
The debug rendering is only enabled in two scenarios:
- When the component itself is selected in the scene tree tab.
- When debug rendering is enabled for all components with the component visualize menu (this is the one you found).

The reason why you got a circle in the center of your camera is because it's trying to render the camera entity that you're currently using; causing this weird circle. 

The circle should be easy to fix, just disable the debug rendering for the active camera (I'll have a look at that). But the component visualization in general is more difficult as it's a generic system for all components. I agree that it's unintuitive at first.

**Comment by jamesmintram** [comment]
>When the component itself is selected in the scene tree tab

Ok, I don't think I saw that. Which was my biggest problem. I have the camera selected, I could see the transform gizmos, but I had no idea where the camera was facing.

Unless having the item selected in the scene tree is different from clicking to select it in the editor view? (I can't check this until later today)

**Comment by frank-ourmachinery** [comment]
You probably had the entity selected and not the camera component on that entity.

**Comment by jamesmintram** [comment]
> You probably had the entity selected and not the camera component on that entity.
So I checked this out and you are right. The catch is (which you are probably aware of :) ) the camera entity I am using is from Core - so I cannot select the camera component without overriding it.

**Comment by tobias-ourmachinery** [comment]
We're aware that it's a bit confusing from a usability point of view that:

1. Non-overridden components can't be selected in the Entity Tree Tab.
2. Non-overridden properties won't show its values in the Properties Tab. #528 

We will try to improve on that behavior. For now I will close this as by-design.
