### ISSUE TITLE
GLTF animations became few times longer.

### ISSUE THREAD

**Issue by ProtonGustave** [OurMachinery/themachinery-public#651]
[Anim.zip](https://github.com/OurMachinery/themachinery-public/files/6867274/Anim.zip)

For example Axe_Attack1 animation. I'm trying to play animation with Animation Simple Player component. In Godot same animation plays for 1.667 seconds which is as it should be. Model is imported from Blender.

**Comment by tobias-ourmachinery** [comment]
I might be missing something but just importing it and checking it in the preview tab indicates that the playback does happen in 1.667 seconds. What are you seeing on your end?

![image](https://user-images.githubusercontent.com/26548681/126758561-74b3c8b8-7d36-4edd-835b-e602b0fff4a0.png)

**Comment by ProtonGustave** [comment]
From discord chat we figured out that i have Ticks Per Second equal to 24 but it should be 1000 for normal speed.
Looks like it's assimp problem
https://github.com/assimp/assimp/issues/3162

**Comment by simon-ourmachinery** [comment]
Disocrd reference https://discord.com/channels/690290013585408136/690290014202233044/868046300208332840

**Comment by simon-ourmachinery** [comment]
OS: Linux

**Comment by raphael-ourmachinery** [comment]
I'll use a version of Assimp from same date of Windows version, because trying to use a more recent version (just before gltf macro redefinitions) fixed the issue with this gltf asset, but broke this fbx animation, so I think is better to keep the importer consistent between OSes.
[man.fbx.zip](https://github.com/OurMachinery/themachinery-public/files/6893072/man.fbx.zip)
