### ISSUE TITLE
Notes on add node menu UX

### ISSUE THREAD

**Issue by LaylBongers** [OurMachinery/themachinery-public#658]
The UX of the nodes menu feels messy and jumps all over the place in terms of indentation. Making this more consistent would make this more usable. For this as well Blender has a few good UX examples that can be looked at.
![the-machinery_7hdi7yjN6K](https://user-images.githubusercontent.com/3094382/127039703-e2ce3dc4-34df-4e7c-a560-eedb093f23ce.png)
![blender_8kBrgPi2pO](https://user-images.githubusercontent.com/3094382/127040421-1f796344-d53b-478c-a291-eeadbe4f24ee.png)
![blender_lXkvAGWDrc](https://user-images.githubusercontent.com/3094382/127040429-f53b4da8-f391-4aa4-bfec-de1c724f67ce.png)
![blender_oav11fFvpK](https://user-images.githubusercontent.com/3094382/127040433-d58852c3-1e92-4f4f-a909-6965455a62af.png)

**Comment by niklas-ourmachinery** [comment]
Thank you for the feedback.

If you don't mind, can you split this up into separate issues... it is tricky to manage issues that has multiple things in them. Maybe keep this issue for (3), since that one has the most pictures in it, and create new ones for (1), (2) and (4).

As for (5), yes we definitely plan to deprecate things going forward... it's a bit of a balancing act... deprecate too little and thing stagnate, deprecate too much and users will get annoyed about things changing and not working anymore. We'll do our best to find a good balance.

**Comment by LaylBongers** [comment]
I'll split up the issue, thanks for taking a look!

**Comment by LaylBongers** [comment]
I've moved 1, 2, and 4 to separate issues, and removed 5:
#659 
#660 
#661

**Comment by niklas-ourmachinery** [comment]
Thank you!

**Comment by simon-ourmachinery** [comment]
@frank-ourmachinery  @14413d19ef94d8a65e8eae6a579ad3c335fef758 made the categories basically useless. Maybe we should reconsider the whole way we display them.

**Comment by simon-ourmachinery** [comment]
<img width="415" alt="image" src="https://user-images.githubusercontent.com/70658708/178064866-b7e374d6-0a1c-4f37-918b-dac0dc43fb52.png">

**Comment by frank-ourmachinery** [comment]
A few changes have been made to the display of the categorised popup item picker.
- Items are no longer inlined if they only contain one item, as you said this made it harder to navigate.
- Everything is now alphabetically ordered rather than partially on the matching scores. This again makes it easier to navigate.

![image](https://user-images.githubusercontent.com/70658773/180952204-acd87dbe-9bc7-445d-8e27-409a1d87e150.png)
![image](https://user-images.githubusercontent.com/70658773/180952266-4cad3de4-ecee-4d8f-8a0c-1cea35a5b382.png)
