### ISSUE TITLE
Notes on node wire UX

### ISSUE THREAD

**Issue by LaylBongers** [OurMachinery/themachinery-public#660]
Dragging and moving lines isn't as clear as in other software. I personally find it very clunky to have to select-delete-recreate a connection rather than being able to move it from one node to another. Notably Blender's node interface has had a lot of UX work done on it, and could be a good reference:
![127038268-4a73e415-c3f9-43b6-bfed-542707775124](https://user-images.githubusercontent.com/3094382/127045078-a591315f-a0c3-45d1-a4f3-ed83f67988ae.gif)

**Comment by karl-zylinski-ourmachinery** [comment]
I have addressed this in this commit: https://github.com/OurMachinery/themachinery/commit/9877201936860d60fed4d7aa5f4ea80cd15d95d1

You can now click and drag at the end connector to move the connection. For event connections you instead click and drag on start connector. Releasing the connection in an empty space pops the create node menu, you can press delete to remove the connection while you drag it.

It also works to just click the connector to move it without holding mouse button.

The only thing that doesn't work is to click the start connector to move the start point, since you can have multiple outgoing connections (in the non-event connection case, for events the opposite is true). This can maybe be fixed by holding a key when you click the connector, which starts a special connect operation that moves the start point of one or many connections connected there.
