### ISSUE TITLE
Overriding components UX concern

### ISSUE THREAD

**Issue by DaveTheGameDev** [OurMachinery/themachinery-public#668]
Overriding components show their default as grayed out. To me personally it implies I cannot edit the value. 
When you change it, the value goes back to white and does not show it actually is now not the default value.

![image](https://user-images.githubusercontent.com/21057342/127673520-9471e0a9-4842-4468-81ef-6d715b910e84.png)

#528 has some UX improvements that could go nicely with this.

**Comment by DaveTheGameDev** [comment]
An improvement would be to make it white by default and show an icon to show the new value is not default, with an option to press it to revert it.

**Comment by niklas-ourmachinery** [comment]
The gray color means that the value is "inherited", white means it is edited locally.

I see the potential confusion that the value looks "disabled", but I'm a bit unsure about what would be a better approach. We could use a different color maybe, but too many colors can make the interface feel "loud".

Using an icon can be tricky, because whatever visual way we indicate this needs to work over a wide range of different controls. For example, in the Vector3 editor, we would need to show a separate icon for each field of the Vector3.

If you edit a value and change it back to the original value it won't go back to being gray, because it's still "edited locally". What this means is that it will keep its current value even if the parent value is changed.

You can revert back to the parent value (and make it gray again) by right-clicking on it.

**Comment by karl-zylinski-ourmachinery** [comment]
The colors of overridden components etc have been reworked a lot recently. The disabled state is much more grayed out than the 'inherted' state you show above, so the confusion should be gone now.
