### ISSUE TITLE
more than one simulate entry in one asset

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#678]
I think it would be beneficial if the user could add more than one entry per asset. This allows for more flexibility.

**Comment by karl-zylinski-ourmachinery** [comment]
Making the Simulate Entry asset contain re-orderable list of simulate entry interfaces is probably a good idea.

Also, like we talked about on chat, maybe the simulate entries should actually be converted into systems instead of being manually managed by the simulate tab. I.e. the simulate entries chosen get systems created on simulate start, which makes ordering of the simulate entries possible. Lastly, like mentioned here https://github.com/OurMachinery/themachinery-public/issues/677 startup and shutdown systems might  be a good idea, the start and stop functions on the simulate entry interface would register as such systems.

**Comment by karl-zylinski-ourmachinery** [comment]
The Simulation Entry Component introduced in 2021.8 supports multiple entries.
