### ISSUE TITLE
Entity Tree View unwanted rename

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#697]
having two objects with different names, clicking on in the hierarchy and modifying the name without pressing enter, and immediately selecting the other object from the hierarchy will rename the newly selected node (both will end up with the same name)

> an update to the name bug, even without modifying the name of first object this happens

Source:https://discord.com/channels/690290013585408136/873667089058127923/873672551585415230 by annoying camper

**Comment by simon-ourmachinery** [comment]
![image](https://user-images.githubusercontent.com/70658708/128614523-ccc4a658-b2ac-44f5-8adb-e440f9d7f30d.png)

> the third (unwanted rename) bug is easy to reproduce, just click according to the image, 1, 2, 3 the first node name will overwrite the second clicked node name

**Comment by niklas-ourmachinery** [comment]
**Bug fix notes:**

This comes from the `stopped_editing` concept. We detect that the *Name* field has lost focus, so we set the `stopped_editing` flag so that the changes will be commited the next time the *Name* field is drawn.

However, the focus was lost because the user clicked on a different entity and now the *Properties* tab is showing that entity, so when the *Name* control wants to commit the changes, it is committing to a different entity.

We could fix this by clearing out `stopped_editing` when we process `if (pv->has_next_objects)`. However, this is not ideal. If we do this, the name of the first object will be changed and the second object will not be, but since we have done a "committing" change, the change will not appear in the undo stack and cannot be undone.

Getting a proper commit with an undo stack is a bit tricky... we need the Name Control to run so it can commit its changes properly, but if something else is being displayed in the properties tab, the Name Control is no more, so it can never commit the changes.

I think we can fix it by introducing another frame delay... if `stopped_editing` is *true*, we wait with switching to `pv->next_objects` until the next frame, so that the existing control gets a chance to process the lost focus event. It feels a bit iffy to introduce even more frame delays though.

**Comment by niklas-ourmachinery** [comment]
I pushed a fix for this.
