### ISSUE TITLE
Using the keyboard shortcut to change the zoom level of the editor triggers it multiple times

### ISSUE THREAD

**Issue by geekrelief** [OurMachinery/themachinery-public#713]
Here I'm using the shortcuts zoom. I added debug info to display the scale each time it changes.  One keypress triggers it multiple times. Toggling back and forth between zoom in and out enough times and you'll ping pong between the extremes.

https://user-images.githubusercontent.com/27040/128896752-066e107d-f5c6-46a3-af69-3e1f2a26c3bd.mp4

When debugging from Visual Studio, if I put a break point where the scale changes, then the scale updates correctly. It seems like the keyboard shortcut is triggering multiple times. Using the menu to options, it works fine.

**Comment by niklas-ourmachinery** [comment]
I think this is a general issue that if the engine "stalls" for a couple of frames because it is doing something "expensive" (like changing the zoom level, which requires new font textures to be generated) we can get multiple key presses or mouse clicks. We should address this.

A related issue I've seen is that double-clicking sometimes doesn't work if the first click causes the engine to stall (because it's loading a slow preview).

**Comment by niklas-ourmachinery** [comment]
Fixed for 2021.8
