### ISSUE TITLE
Entity Override of child entity does not allow me to overwrite the components automatically, I need to right click and do that again

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#720]
related to #528 & #447

**Comment by niklas-ourmachinery** [comment]
This is expected behavior... you can override an item without overriding its children.

Note that you can expand the tree and override the component without overriding the entity first to do this in fewer steps. Or you can use the shortcut of double-clicking to override the component.

**Comment by simon-ourmachinery** [comment]
It feels a bit off to me because, on the one hand, I expected that when I override the parent entity that I can modify its components directly without needing to specify this again.

**Comment by niklas-ourmachinery** [comment]
I don't think we want to change this behavior though... we should be explicit about which components of an entity are overridden, rather than overriding all the entities (and child entities?) when an entity is overridden. I think this is just a thing that we have to "teach" the users.

I'm all for making improvements to the UI that makes this feel "smoother" though.

**Comment by simon-ourmachinery** [comment]
I think I than close this and add by design. If anyone has an issue with this later we can reopen it and discuss what could be done better. 

Since I would not know how to make this smoother.
