### ISSUE TITLE
Shift+Click for select doesn't always work

### ISSUE THREAD

**Issue by julhe** [OurMachinery/themachinery-public#721]
Notice how it works the first two times. After then, it becomes imposible to do a shift-click select, and the view just jumps to my selected entity.

https://user-images.githubusercontent.com/18037091/129203174-61f21c05-9f7f-4072-bff4-a21405bfeff9.mp4

**Comment by leonardo-ourmachinery** [comment]
Tried again to reproduce it... the bug is definitively there as I was able to repro it one single time during something like 100 tries.
But it's quite tricky for me to identify the issue without a stable repro case as I can't step into the debugger at all... @julhe do you have a specific sequence of actions that I can follow to repro the bug with a reasonable probability? I'm guessing that if you were able to record it you had a pretty high repro rate... (sorry for bothering, I tried with recreating your 32 entities setup but no luck)

**Comment by leonardo-ourmachinery** [comment]
Fixed in Master, will be available in 2022.2.
