### ISSUE TITLE
request : non-commercial educational license for 'themachinery' source code

### ISSUE THREAD

**Issue by aerosayan** [OurMachinery/themachinery-public#727]
Dear OurMachinery team,

I read the header files included in the download bundle for the game engine.

It is quite amazing that currently your company is providing very affordable licenses for your game engine to indie devs.

However I was interested in your game engine due to the design decision of using C as the programming language, when everyone else in the game industry seems to use C++.

I read through all the blogs on your website, and was interested to learn more about how you're developing a massively complex system, such as a game engine, only using C.  I think that your game engine source code can be a great example for students to learn from.

I do High Performance Computing for a living, and I found your method of coding and project organization very educational.

So, I'm humbly requesting for a new tier of license for non-commercial educational purposes. As in, users won't profit from making any product using the game engine, but will have access to the source code for educational and non-commercial use, if it is acceptable by your team.

I know there are business decisions that might be complex, and creating such a license might be difficult, and you obviously might want to protect your intellectual property and keep it closed source.

So, in case if it is possible in future, kindly take my request into consideration.

Yours faithfully
~sayan

**Comment by niklas-ourmachinery** [comment]
Thanks for your input.

We've gotten similar requests before. Our current thinking is that people who are interested in learning from the source code can get an Indie Pro license (since it's already pretty affordable). Or, if they are in school, they can get our [Academic License](https://ourmachinery.com/academic.html)... but we may revise this in the future.

I'll close this issue, since it isn't really a Bug or Feature request... but feel free to keep discussing it in the [Discussions](https://github.com/OurMachinery/themachinery-public/discussions).
