### ISSUE TITLE
Graph connection drawing issue at high zoom levels

### ISSUE THREAD

**Issue by karl-zylinski-ourmachinery** [OurMachinery/themachinery-public#784]
Setup a graph like this... Place the notes similarly (my grid is at size 30, the default).
![image](https://user-images.githubusercontent.com/57644882/131856441-ba4973a5-bffb-470f-bedf-3253855cfe45.png)

Then zoom closely into the right node. The connection will be broken at some high zoom levels. I think it is due to `stroke_bezier` rejecting the segment when it shouldn't.
![image](https://user-images.githubusercontent.com/57644882/131856474-5ebee5c4-95fd-4c4b-8a0a-6f2e1e7537af.png)

**Comment by niklas-ourmachinery** [comment]
What happens here is this:

* As you zoom in on a bezier curve it gets split up into more and more individual line segments for drawing.
* We reserve a fixed amount of memory for drawing by calling `tm_ui_api->reserve_draw_memory()`.
* At some point, this memory will not be enough to hold all the line segments.

There are several possible fixes:

* Rewrite the draw functions so they can grow the memory buffers themselves when they need more memory.
* Implement software clipping in `private__stroke_polyline_no_feather()` so that we only draw the line segments that are actually visible.
* Limit the number of subdivisions we make for a bezier curve.

**Comment by niklas-ourmachinery** [comment]
I did a quick fix for this where it will drop the quality of the bezier curve if there is not enough memory to render it at the desired quality.
