### ISSUE TITLE
PhysX error lead to black screen.

### ISSUE THREAD

**Issue by ProtonGustave** [OurMachinery/themachinery-public#789]
When i try to go on right(i'm not sure what's up with right) it starts to print errors and screen become black.

Video:
https://discord.com/channels/690290013585408136/779314091990319104/885142354846167040

Start of errors(then they repeat):
![image](https://user-images.githubusercontent.com/35541456/132510112-fca4e86d-0e85-4bea-b3d8-01235cc276fc.png)

**Comment by karll-ourmachinery** [comment]
Can you share the code snippet (or graph) responsible for the character rotation? 

Some 3D rotations are undefined under specific situations, which cause singularities and possibly NaN values, if unhandled it will cascade. The character position may have an absurd value because of this behaviour, which may be causing the black screen.

**Comment by ProtonGustave** [comment]
@karll-ourmachinery thank you, problem was in my quat calculation indeed, it became NaN at some point.

**Comment by ProtonGustave** [comment]
I guess you assumed it's rotation problem because of "unitDir" in logs?
