### ISSUE TITLE
Material alpha blend mode is not respected

### ISSUE THREAD

**Issue by infosia** [OurMachinery/themachinery-public#795]
Testing material alpha blend mode with [Khronos glTF AlphaBlendModeTest](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AlphaBlendModeTest) shows wrong figure.

How to reproduce:
1. Download glTF from  [Khronos glTF AlphaBlendModeTest](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AlphaBlendModeTest)
2. Import [glTF](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AlphaBlendModeTest/glTF) 
3. See the results

![Capture](https://user-images.githubusercontent.com/1661068/133172434-bea8a5b6-f020-410d-9946-288051d668fd.PNG)

Seems like both alpha bend and mask (alpha cutoff) is not respected.

Expected:
![screenshot_large](https://user-images.githubusercontent.com/1661068/133172444-9172bb1e-5bc0-4598-8596-f5347349fcda.jpg)

**Comment by frank-ourmachinery** [comment]
I've added an opacity cutoff output to the DCC material node, connecting that to the lit outputs opacity output solves one of the issues. The blending issue is a bit trickier as the opacity is stored in the metallic roughness texture. Currently, we only support opacity in the alpha channel of the diffuse texture or as a fully separate texture. This probably warrants a closer look at which types of opacity inputs we want to support by default.

**Comment by frank-ourmachinery** [comment]
A bit of additional processing is currently necessary to get models with transparent material properties to work.
The opacity cutoff variable from the DCC asset is now set by default for materials that use the default opacity creation graph.
The blend however needs to be set manually for now. The problem is that the blending changes the shader type as it needs to render in a different layer, which currently cannot be changed automatically. One option would be to add another default DCC material for blended opacity materials, but I'm a bit hesitant about adding another version with only a minor change.
![image](https://user-images.githubusercontent.com/70658773/151134056-56eaab3d-aef3-4a59-9be5-cbfb7fedb328.png)
