### ISSUE TITLE
Spline Component sample should allow > 180 degree rotations

### ISSUE THREAD

**Issue by eigenbom** [OurMachinery/themachinery-public#803]
The Spline sample acts strangely with respect to the rotation values. For instance

* When you input 360 into a field it wraps to 0
* Inputting R.y=180 instantly converts it to R.x = 180, R.z = 180

This coupling between target values and internal quaternion makes this sample confusing to play with. I think it'd be clearer and more useful if the rotation here was an arbitrary unconstrainted set of euler angles.

![image](https://user-images.githubusercontent.com/1103761/134123527-92e2ec2c-bc6c-481c-9be6-b8ffd87c5edd.png)

**Comment by niklas-ourmachinery** [comment]
They both have advantages and disadvantages. With Euler angles you can specify angles > 360 degrees and have the object spin multiple times. Also, whatever you enter stays as entered.

However, interpolation in Euler space is subject to things like Gimbal lock and can be confusing while interpolation in quaternion space is more natural.

We can't really change this component to do interpolation in Euler space, because that would change its behavior, so if anyone is using the component for something, it might break. Also since this is just a sample I don't think it matters that much.

If you want a similar component that does interpolation in Euler space, you could create a copy of this one.
