### ISSUE TITLE
Float Expression node doesn't output until you reset variable value

### ISSUE THREAD

**Issue by eigenbom** [OurMachinery/themachinery-public#811]
* create float expression node with two variables
* set expression = 'a'
* attach input to 'a'
* observe there's no output
* highlight 'b' value and press enter (don't need to change value)
* observe node now has output

![expression_node](https://user-images.githubusercontent.com/1103761/134615021-0b44e6f8-75df-4b9f-bea2-a51d402c4984.gif)

**Comment by niklas-ourmachinery** [comment]
The issue is that the variables are marked optional... so the Float Expression node doesn't show an error if they're not connected... but they are actually treated as required, so it won't compute a result if they're not there.

`b` is initially not supplied... this is a bit hard to see in the interface... it is marked by the connector being hollow. When you edit the `b` field, the variable becomes supplied (with the default value zero).

There are two possible fixes here:

* Make the variables required -- in this case it will be an error to not connect all of them.
* Make the variables optional -- in this case it they will default to 0.

Arguments can be made for both cases:

* Required variables lets the user easier detect errors where they've failed to supply a variable.
* Optional variables gives less confusion about being in an "error state".

Thinking about it a bit, I think optional variables is the best approach.

(I noticed we're not terrible consistent with this in other math nodes... some use optional parameters, some required, should probably clean that up.)

**Comment by niklas-ourmachinery** [comment]
Fixed for 2021.9.
