### ISSUE TITLE
Download Samples: Missing a remove, re-download button

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#859]
Sometimes when playing with the samples you completely mess them up and you are missing a redownload button. The workflow of going to the sample on the HDD and deleting it and reopening the tab is kinda long would be a workflow improvement to just have a delete button to remove them and a redownload button.

**Comment by leonardo-ourmachinery** [comment]
I've made it so that it's always possible to "Get" a sample project and download it at a new path.
The "Open" button will instead only be activated once the sample is downloaded the first time.
(Once you re-download the sample, clicking on the "Open" button will open the project you just downloaded).

There were another bunch of other viable options, but I felt this was the most reasonable one.
