### ISSUE TITLE
I want to be able to target specific framerates when simulating.

### ISSUE THREAD

**Issue by hsjunnesson** [OurMachinery/themachinery-public#871]
For instance - when recording for a game trailer, it's useful to be able to render at a high framerate, to do slow-motion effects in when editing. Some games will lock their framerate at 30 fps on low-spec platforms.

**Comment by leonardo-ourmachinery** [comment]
Fixed for 2021.11
You can now Cap the framerate to some common values in the Simulate->Cap framerate menu of the simulate tab.

In the future I think we might want to "save" this information around so that you don't have to set this every time (same for target resolution I would say), and just say that you want to target 1080p/30FPS for the entire length of the project, but that's another story.
