### ISSUE TITLE
Empty window keeps opening after closing application

### ISSUE THREAD

**Issue by frank-ourmachinery** [OurMachinery/themachinery-public#911]
Steps to reproduce:
- Drag a tab outside a tabwell to create a new window.
- Close the newly moved tab.
- Close the newly-created window.
- Close The Machinery.
- Re-launch The Machinery.
- An empty window now shows up.

The only way to solve this issue (that I've found) is to destroy the project settings.

**Comment by niklas-ourmachinery** [comment]
I think this is kind of "expected" behavior the way things work now... on restart it will restore any windows that were "recently" closed before the application shut down.

But I think we should probably make an exception and not restore any empty windows... it's not generally very helpful.

**Comment by leonardo-ourmachinery** [comment]
Yes, we should avoid saving empty windows altogether.
Related: I think we may want to automatically close empty windows when their last tab is closed/moved.

**Comment by leonardo-ourmachinery** [comment]
I made it so that we don't "save" empty windows nor empty workspaces. (A window is considered empty if all of its workspaces are empty, and a workspace is considered empty if it doesn't have any tab).

I'm not sure we want to auto-close empty windows when you drag the last tab out of it, so closing this for now.
