### ISSUE TITLE
graph - add node - better organisation of sub-category results

### ISSUE THREAD

**Issue by eigenbom** [OurMachinery/themachinery-public#926]
the add node search results could be more organised. see the results for "shader" for instance ... 

![image](https://user-images.githubusercontent.com/1103761/146659706-f35fb7ef-e0e1-4d77-ac50-80a7dd9be19d.png)

**Comment by niklas-ourmachinery** [comment]
Agreed, this looks really messy... I think we need to rethink how the list should work when searching/filtering.

**Comment by simon-ourmachinery** [comment]
#922

**Comment by frank-ourmachinery** [comment]
The search algorithm and categorisation have gotten an update in master.
Bellow, you can see the new default state of searching for `shader`.

You can note that `Output` and `Simulation` get expanded by default as they contain matching nodes (**Shader** Instance and GPUSim - Update He**ader**).

Note as well that the Shader category is not expanded as it only matches the category name rather than any individual item.
This makes the list much more concise.

![image](https://user-images.githubusercontent.com/70658773/180950669-9236507f-88ac-47c8-9d71-9ddf21df528e.png)
![image](https://user-images.githubusercontent.com/70658773/180950932-9909e040-8a18-4a17-8403-cac740432ea4.png)
