### ISSUE TITLE
Broken entity prototype removal, instance is still there, but empty

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#94]
- Remove a prototype of an entity that has an instance in a level
- The instance is still there in the level (still yellow in the entity tree!), but it is is empty. Saving and reloading the project even makes it lose the name.

The behavior I expect:
- Upon prototype removal, it checks for instances. If such exists, it warns the user that there are instances, and that removing this prototype will break the prototype relation.
- If the user chooses to go through with the prototype removal, then all the instances become separate copies of the prototype.

Perhaps we can have an extra prototype relation which is called TM_TT_PROTOTYPE_RELATION_BROKEN (as in broken connection between instance and prototype). Entities with such a relation are marked red in the entity tree. This broken prototype relation is changed to TM_TT_PROTOTYPE_RELATION_ADDED if we make additional changes to the entity (I think this is OK, since making additional changes to a red entity signals  that the user has seen the brokenness and is OK with it). Or maybe we should just add this "broken" flag to the entities themselves since this may be a very entity-specific problem, i.e. have a "broken" flag on entities that is reset once we make more changes to the entity.

**Comment by karl-ourmachinery** [comment]
Thought about this a bit. A simpler solution is the following:
* Keep everything as it is (but perhaps warn when removing the prototype)
* Add an item to the context menu of the instance that when clicked 'extracts' the instance, i.e. makes it a copy and breaks the relation.
* Later, we could add something like 'extract all instances' to the prototype context menu, if needed.

**Comment by niklas-ourmachinery** [comment]
Thought a little bit a bout this. When it comes to UX design some good principles are:

* Don't interrupt the user with warnings, alerts, etc. Assume that if the user takes an action the user wants to do that action.
* Make sure that actions can be undone/reverted so if the user did not intend to take the action, the old state can be restored.
* User actions should not be able to create a "broken" state. The state after a user action should still be valid.

Given these constraint I think the best behavior if a prototype is deleted is:

* Automatically "break" all prototype relationships.
* Instances of the prototype become ADDED objects without a prototype.
* Any values inherited from the prototype are copied into the instance.

As for implementing this, it will be quite expensive, because we don't have a lookup table from the prototype to all the objects that instance it, so finding that would require us to scan the entire Truth.

We could either add such a lookup table, which I'm not super-psyched about, because it is another piece of "state" that needs to be kept synchronized and a potential source of error. Or, we could perhaps do something simpler, such as set a bit in objects that are used as prototypes so that we only have to do the full Truth scan when an actual prototype is deleted.

Not sure... this seems like a very important bug to fix... but I'm not 100 % sure what the best solution is, so maybe mull over it a bit more.

**Comment by niklas-ourmachinery** [comment]
Fixed for 2020.4.a.

* It uses the somewhat expensive lookup strategy that we are already using for looking up instances.
* I did not put in a warning... as I said I think it's better not to interrupt the user with warnings.
