### ISSUE TITLE
Shift dragging in to duplicate in scene changes the name of the entity

### ISSUE THREAD

**Issue by LoffanElemental** [OurMachinery/themachinery-public#951]
If you duplicate an entity in the entity tree, I think the name should stay the same so you can see how many instances of that entity you have done. This is true if you right click and choose duplicate. But if shift drag in the scene it adds a new number in the end. For me this now looks like two different entities and is very confusing.
![Shift dragging_error_01](https://user-images.githubusercontent.com/94915027/148100530-b2508910-86cc-46f4-91d6-ef17a9b808ef.JPG)
![Shift dragging_error_02](https://user-images.githubusercontent.com/94915027/148100532-433fd46a-f324-4185-b467-a55517d5f5e8.JPG)
u

**Comment by niklas-ourmachinery** [comment]
When you duplicate an entity it tries to auto enumerate so that each entity gets a unique name. This makes it possible to tell the entities apart in scripts etc.

So if you have an entity named `apple` and you duplicate it, it will become `apple_1`. If you have `apple_103` and duplicate it, it will become `apple_104`.

Unfortunately, this auto enumeration algorithm also duplicates `scaffold_1x1x1` to `scaffold_1x1x2` -- i.e. it thinks the last number is an enumeration number.

I don't know if we should try to change the algorithm... it might be tricky to distinguish things that look like enumeration numbers from actual enumeration numbers...

A workaround is to name your entities to something that doesn't end in a digit, e.g. `scaffold_1x1x1m` then the duplicate will be `scaffold_1x1x1m_1`.

**Comment by LoffanElemental** [comment]
Feels weird to me as a content creator that this number should change the actual name. Could it not be a number in the properties window instead? Also Why is the right click duplicate command not adding this?

**Comment by LoffanElemental** [comment]
How can I as a content creator quickly see that these are the same entity if thy have different names?

**Comment by LoffanElemental** [comment]
And thanks for the  workaround!

**Comment by LoffanElemental** [comment]
I have also detected a lot of duplications of entities when shift click dragging them. It seams to happen mostly on entities made up of sub entities. But you need to multiselect entities for it to happen. I have had up to 5 entities stacked on top of eachother

**Comment by niklas-ourmachinery** [comment]
* The point of changing the name *is* to be able to distinguish the entities, so you know that `tree_1` and `tree_2073` are different. It can be confusing if you have a long list of entities that all have the same name.
* I think it's a bug that right-click duplicate doesn't add this. It should use the same algorithm.
* You can tell that `tree_1` and `tree_2073` are instances of the `tree` prototype, because the names both start with `tree`.
* I'll see if I can repro the extra duplication.

**Comment by niklas-ourmachinery** [comment]
I've verified an issue where you can get extra duplication. If you have a multi-selection of both an child and its parent and you shift-drag, then the parent object will be duplicated, but also the child will be duplicated inside the parent.

In this example, I had `Stack` and `Row (bottom)` selected and shift-dragged:

![image](https://user-images.githubusercontent.com/26548514/150235235-edce6dcf-5b55-4148-8b91-2c8e8af2b8b2.png)

It created `Stack_1` (which I think is correct), but also `Row (bottom)_1` which I think is incorrect. In this case only the parent/root should be duplicated.

Does this seem like the same behavior you were seeing?

**Comment by LoffanElemental** [comment]
> * The point of changing the name _is_ to be able to distinguish the entities, so you know that `tree_1` and `tree_2073` are different. It can be confusing if you have a long list of entities that all have the same name.
> * I think it's a bug that right-click duplicate doesn't add this. It should use the same algorithm.
> * You can tell that `tree_1` and `tree_2073` are instances of the `tree` prototype, because the names both start with `tree`.
> * I'll see if I can repro the extra duplication.

So if I have made this in a scene:

tree_birch_medium_01
tree_birch_medium_02
tree_birch_medium_03

When working with entities in the Avalanche engine for example, this would mean that I have three different entities. But in Our Machinery it could mean two different things. That I have three different entities or that I have one entity that is instanced two times! Adding hardcoded restrictions on what an name can be is not a good approach in my mind. But if you really want this approach I think entity names that have numbers in the end should be possible to make.

**Comment by LoffanElemental** [comment]
> I've verified an issue where you can get extra duplication. If you have a multi-selection of both an child and its parent and you shift-drag, then the parent object will be duplicated, but also the child will be duplicated inside the parent.
> 
> In this example, I had `Stack` and `Row (bottom)` selected and shift-dragged:
> 
> ![image](https://user-images.githubusercontent.com/26548514/150235235-edce6dcf-5b55-4148-8b91-2c8e8af2b8b2.png)
> 
> It created `Stack_1` (which I think is correct), but also `Row (bottom)_1` which I think is incorrect. In this case only the parent/root should be duplicated.
> 
> Does this seem like the same behavior you were seeing?

It could be! If you release the fix for this and tell Christian Nilsendahl (Elemental) He can update and I can give it a try

**Comment by ElementalAndy** [comment]
Maybe changing the auto enumeration to use parenthesis would be a good compromise?

E.g. duplicating the entities
```
tree_birch_medium_01
tree_birch_medium_02
tree_birch_medium_03
```
would become
```
tree_birch_medium_01(1)
tree_birch_medium_02(1)
tree_birch_medium_03(1)
```

**Comment by niklas-ourmachinery** [comment]
So I think there's multiple things going on here.

1. I think your expectation that the entity name should be the asset names is a bit off. Entity names are intended to be unique-ish (they are not required to be unique, but it helps if they are, so that you can tell which entity you are talking about when  you are browsing them in a list, etc).
2. If you find it helpful to see *asset names*, as opposed to *entity names* we could perhaps have an option for that in the tree view.
3. I agree that the automatic numbering gets really confusing when you have asset names ending in number... i.e. if you have assets `tree_01` and `tree_02` which is a common use case and you duplicate a `tree_01` asset and it becomes `tree_02`, that's really confusing.

Maybe the auto-enumeration should check if the entity name matches the asset name and in that case add an additional number.

I.e. if you have placed a `tree_01` asset with the name `tree_01`, on duplication we would see that the entity name matches the asset name and know not to go `tree_02` and instead do `tree_01.1`, `tree_01 #1` or something like that.

**Comment by LoffanElemental** [comment]
> So I think there's multiple things going on here.
> 
> 1. I think your expectation that the entity name should be the asset names is a bit off. Entity names are intended to be unique-ish (they are not required to be unique, but it helps if they are, so that you can tell which entity you are talking about when  you are browsing them in a list, etc).
> 2. If you find it helpful to see _asset names_, as opposed to _entity names_ we could perhaps have an option for that in the tree view.
> 3. I agree that the automatic numbering gets really confusing when you have asset names ending in number... i.e. if you have assets `tree_01` and `tree_02` which is a common use case and you duplicate a `tree_01` asset and it becomes `tree_02`, that's really confusing.
> 
> Maybe the auto-enumeration should check if the entity name matches the asset name and in that case add an additional number.
> 
> I.e. if you have placed a `tree_01` asset with the name `tree_01`, on duplication we would see that the entity name matches the asset name and know not to go `tree_02` and instead do `tree_01.1`, `tree_01 #1` or something like that.

I think ElementalAndy's solution or your suggestion both work. As long as it is consistent. So if I always get a (*), .*, or #* when instancing an entity I think it makes sense. Then the original name is intact and I can quickly see what is instanced. 

This how I interpret the suggested solution:

Example 1 ,No suffix number in name:
start entity: **Tree(1)**
Instance entity: **Tree(2)**

Example 2 ,with suffix number in name:
start entity: **Tree01(1)**
Instance entity: **Tree01(2)**

**Comment by niklas-ourmachinery** [comment]
Naming is one of those things were people can have pretty strong ideas about what they want. I'm finding it a bit tricky to come up with something that works well in a lot of scenarios. At the same time I don't want to introduce a bunch of complicated settings for it. Some thoughts:

* I don't like adding an instance number on the first instance... because a lot of things will only have one instance and it feels kind of ugly to have it called `sun #1` etc.

* OTOH, if you do duplicate something, I don't like that the first one is called `tree` and the second one `tree #1` -- at that point it would be nicer to have them called `tree #1` and `tree #2`. One option is that when you do the first copy, the name of the original gets changed to `tree #1`... but I don't know how nice it is to change the name of the thing that is being duplicated.

* I also like for users to be able to use their own numbering schemes and not be forced into a specific format. One nice thing about the current approach is that if the instance is named `tree_007` the duplicate will be `tree_008`, so zero-prefixes, etc are respected.

**Comment by LoffanElemental** [comment]
My main problem when working with a lot of entities right now is that I don't understand what is an instance and what is a unique entity. So I don't think the current approach of automatically renaming my entities is nice. It is hard for me to work with. If I am building a forest, not with code but actually placing assets. I need the ability to see in the tree view what entities that are actually holding the same data. But it feels like we see this thing very differently. Would it be easier with a call or should I prepare some more screenshots to explain better?

**Comment by LoffanElemental** [comment]
For me function is more important then form so your suggestion of "at that point it would be nicer to have them called tree #1 and tree #2" I think is the best option.

**Comment by LoffanElemental** [comment]
But any solution were I can keep track of what entities have the same data in the entity tree view (instances of one entity) are fine by me.

**Comment by niklas-ourmachinery** [comment]
Pushed a fix for this in master.

Duplicates are now named with the parenthesis naming scheme, so `tree_01` duplicates will be `tree_01 (1)`, `tree_01 (2)` etc.

The first instance is still just called `tree_01`.

I think this is a good compromise between the different goals... let's try this out for a bit... If you feel like there is still improvements needed after trying it out for a while, you can open a new issue.

**Comment by LoffanElemental** [comment]
Sounds great to me! I will try it out!
