### ISSUE TITLE
Copy and paste not working

### ISSUE THREAD

**Issue by jamesmintram** [OurMachinery/themachinery-public#972]
- Git master
- Linux 

Click an imported mesh, this selects the mesh entity within the "main" entity - select the "Main parent" entity representing the model. Select the viewport, Ctrl+C then Ctrl+V does nothing.

![image](https://user-images.githubusercontent.com/108040/150004812-28a8b852-d935-4adc-92f8-0b5801cff255.png)

**Comment by leonardo-ourmachinery** [comment]
I'm not sure 100% I understood your issue, but I made it so that if you select something in the Entity Tree and you press Ctrl + C, this happen:

-if you immediately press Ctrl + V (so the object is still highlighted in yellow), the object is "cloned"
-if you click on the Scene Tab (the object will be deselected) and then press Ctrl + V, the same happen (the object is cloned)

Please feel free to reopen if this doesn't fix your issue.
