### ISSUE TITLE
Clicking the Simulate button takes you to the simulate tab instead of starting a new simulation

### ISSUE THREAD

**Issue by jamesmintram** [OurMachinery/themachinery-public#976]
I would expect the "play" button to do the same thing every time (start a new simulation)

To achieve what I wanted (which was 2 simulations running at the same time) I had to manually add another simulation tab.

**Comment by leonardo-ourmachinery** [comment]
Personally I think we could change the behavior so that a new tab is open if the entity you're trying to simulate is not being simulated in one of the simulate tabs that already exist. So if your simulate tab is currently simulating the "sphere" entity and you press Play in the "Box" scene, a new simulate tab is created.

But if your "world" entity is already being simulated in a simulate tab, what's the use case of opening another simulate tab instead of reusing the already existing one?

**Comment by jamesmintram** [comment]
My use case (which admittedly could be a bit weird) was me clicking simulate after rebuilding the simulation plugin. I wanted to see the two versions side by side to compare.

I guess an additional reason for simulating the same entity twice, might be for running multiple simulations for testing a network game. (I haven't really looked into any multiplayer workflows in TM, so this might already be handled)

**Comment by leonardo-ourmachinery** [comment]
For Networking we have special purpose settings where you can specify exactly that: what "kind" of simulate tabs should be opened when you hit the play button in the scene? (one client and one server, two servers and one client, etc) 
(We had to do that as the editor cannot know if you want to start a new simulation tab as a client or as a server when you hit the play button, so you would have to manually set the type for each instance anyway)

Let's leave the issue open for now and see what happens, I'll try to implement the "open new tab if entity is different" thing and see how it feels.

**Comment by leonardo-ourmachinery** [comment]
I just pushed to master the modification I suggested, please try it if you can and let us know what do you think.
We'll test this internally as well to see how it feels and decide if we want to ship it or stay with the current behavior.

I'm closing this for now.
