### ISSUE TITLE
Support for moving Entity Graph Event Wires

### ISSUE THREAD

**Issue by ElementalAndy** [OurMachinery/themachinery-public#997]
As a user I would like to be able to change the execution order of graph nodes by moving the end of an Event Wire.
![move_flow_pin](https://user-images.githubusercontent.com/91697782/152494372-b19cfe9e-f27c-4551-a399-14e43cbafed1.gif)

**Comment by leonardo-ourmachinery** [comment]
Adding a possible "alternative" solution to the problem that we discussed internally.

Quote from internal chat:
> I find it a bit counter-intuitive that if I click on the "outputs" execution paths of a node the editor starts dragging the connection around (which is what I would expect) while if I try to click on the "input" execution path on the other side it thinks I want to connect it to a new node, even if the connection is already filled in.
I think I would prefer it if the behavior was consistent:
-filled connection -> always drag
-empty connection -> always "create new connection"
(It's gonna be tricky for when there are multiple connections that go to the same node, but I think just picking one randomly or the last one would work fine)

<img width="328" alt="image" src="https://user-images.githubusercontent.com/70660839/154042607-f43c35b0-2f52-44c7-9adf-98688e57a14b.png">

<img width="343" alt="image (1)" src="https://user-images.githubusercontent.com/70660839/154042672-a3e020af-9b0d-4221-b3ea-a609f72382e8.png">

<img width="344" alt="image (2)" src="https://user-images.githubusercontent.com/70660839/154042697-d97d9bf3-d19c-4be2-b507-1c52106d1f10.png">

But as Karl said, the problem of this approach is that we'd have to drag potentially multiple connections and that is currently not supported.

**Comment by karl-zylinski-ourmachinery** [comment]
@ElementalAndy In commit https://github.com/OurMachinery/themachinery/commit/d8be440801831dcda4e6bae75ce200d64227c372 I have made it so that any endpoint can be dragged. I also added so that you can hold CTRL in order to make new connections instead of dragging the current one. This applies to both event and non-event connections.

If there are multiple connections into the connector, then a random connection will be dragged. I could make it so that all of them are dragged in a bundle, not sure how useful that is though. Thoughts?

**Comment by ElementalAndy** [comment]
Great, I'll try it out tomorrow.

**Comment by karl-zylinski-ourmachinery** [comment]
@ElementalAndy People on our side are annoyed with "dragging connections" instead of creating new connectors being the default now. What do you think? We are thinking about reversing this so that clicking + dragging always creates a new connection and holding CTRL + clicking + dragging moves any current connection.

**Comment by ElementalAndy** [comment]
I agree that reversing it might be better. An alternative could be to move the wire if the user click and drag the wire close to the connector but not the actual connector.

**Comment by karl-zylinski-ourmachinery** [comment]
I have reversed this now so that CTRL must be held to move the connections.
